### ISSUE TITLE
Client Guide

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#100]
This issue will be to record things that should potentially be added to the PhET-iO Client Guide, when it is created.

**Comment by pixelzoom** [comment]
A couple of things from 3/11/21 design meeting @arouinfar @kathy-phet @pixelzoom 

- [ ] Describe view coordinate frame: +x right, +y DOWN, +angle CLOCKWISE

- [ ] Bond angles are relative to the molecule's angle.  If you want to know the bond angle in global coordinate frame, add the molecule angle.

**Comment by pixelzoom** [comment]
Assigning to @arouinfar.  I don't think this is needed for #87 (research study).  But there's been talk of publishing a production PhET-iO version of this sim.  I don't know what the timeframe is, but this will be needed.

**Comment by arouinfar** [comment]
I completed the client guides in the above commits. I decided against specifically addressing the points in https://github.com/phetsims/molecule-polarity/issues/100#issuecomment-797100428 for a few reasons:
* The information is already in the documentation in Studio
* Duplication makes things less maintainable
* Bond angles are not featured, and it seems weird to call them out
