### ISSUE TITLE
Instrument inputEnabledProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#101]
Related to #85, and after phetsims/scenery#1116 has been completed...

Instrument `inputEnabledProperty` for the following Nodes:

- [x] DiatomicMoleculeNode

- [x] TriatomicMoleculeNode
  atomANode
  atomBNode
  atomCNode
  bondABNode
  bondBCNode

Discuss the plan for common-code UI components used by this sim: 
* HSlider
* Checkbox
* AquaRadioButtonGroup
* ABSwitch

**Comment by zepumph** [comment]
https://github.com/phetsims/scenery/issues/1116 is complete and out for review. You can add the following option to instrument `inputEnabledProperty` for any Node:

`inputEnabledPropertyPhetioInstrumented: true`

This can be done in your sim for common code components also, but any changes needed inside common code will be done in https://github.com/phetsims/scenery/issues/1158.

**Comment by pixelzoom** [comment]
Here's a description of the sim-specific `inputEnabledProperty` elements that were added in the above commits.

The diatomic molecule has only one DragListener (for rotating), so requires only one element:
```
moleculePolarity.twoAtomsScreen.view.moleculeNode.inputEnabledProperty
```

The triatomic molecule has a DragListener on each atom and bond, and they can be individually controlled via these elements:
```
moleculePolarity.threeAtomsScreen.view.moleculeNode.atomANode.inputEnabledProperty
moleculePolarity.threeAtomsScreen.view.moleculeNode.atomBNode.inputEnabledProperty
moleculePolarity.threeAtomsScreen.view.moleculeNode.atomCNode.inputEnabledProperty
moleculePolarity.threeAtomsScreen.view.moleculeNode.bondABNode.inputEnabledProperty
moleculePolarity.threeAtomsScreen.view.moleculeNode.bondsBCNode.inputEnabledProperty
```

The triatomic molecule also has this element at the top-level. Setting it to `false` will disable interaction for all child elements of `moleculeNode`.
```
moleculePolarity.threeAtomsScreen.view.moleculeNode.inputEnabledProperty
```

@arouinfar @kathy-phet please review in master.  Anything else for sim-specific `inputEnabledProperty`?   Then we can discuss what needs to be completed for common-code `inputEnabledProperty`.

**Comment by pixelzoom** [comment]
Need to turn off hint arrows for triatomic atoms that are inputEnabledProperty false.

**Comment by pixelzoom** [comment]
> Need to turn off hint arrows for triatomic atoms that are inputEnabledProperty false.

Done in the above commit. This was a little tricky because the visiblity of ech hint arrow involves 3 things: inputEnabledProperty for the molecule, inputEnabledProperty for the atom, and whether the user has changed the molecule. 

@arouinfar ready for review.

**Comment by arouinfar** [comment]
@pixelzoom looks good on the Three Atoms screen, but I think we'll want to do the same for the Two Atoms screen and have `moleculePolarity.twoAtomsScreen.view.moleculeNode.hintArrowsNode.visibleProperty` listening to `moleculePolarity.twoAtomsScreen.view.moleculeNode.inputEnabledProperty`.

**Comment by pixelzoom** [comment]
Ah right, the Two Atoms screen... duh.

Done in the above commit.  Please re-test the Three Atoms screen, because I made some improvements in the implementation there, informed by the Two Atoms implementation.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom.
