### ISSUE TITLE
State of hint arrows is not saved

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#106]
This was reported by @phet-steele in https://github.com/phetsims/molecule-polarity/issues/105, for phetsims/QA/issues/627:
> * Cue arrows around the atoms do not stay hidden. They shouldn't be back.

But it's a separate issue, and has nothing to do with the other things reported in #105.

To reproduce:

1. Start the sim in Studio
2. Go to Two Atoms screen
3. Move the molecule, so that the hint arrows go away
4. Press Preview in Studio. Note that the hint arrows appear in the preview sim.

The hint arrows are not instrumented, nor is their state.  This will take some work, and will likely involve a new PhET-iO-only instrumented Property.

@arouinfar How do you want to proceed? Should the state of hint arrows be saved/restored?  And does this need to be addressed for the #87 (RC version for research study)?

**Comment by arouinfar** [comment]
> @arouinfar How do you want to proceed? Should the state of hint arrows be saved/restored? And does this need to be addressed for the #87 (RC version for research study)?

The state of the arrows should be saved/restored. If that means individually instrumenting the hint arrows, that's fine, we just won't feature them. If this was purely about customizing the sim in studio and previewing it, I might dismiss it for #87. Playing around in the state wrapper reveals strange things.

* On startup, grab atom A and drag it down in the upstream sim. Sometimes the hint arrows remain visible in the downstream sim, and sometimes they correctly disappear (if there's a pattern, I haven't figured it out). Here are two examples of what I saw. Both times I refreshed the browser tab before interacting.
![image](https://user-images.githubusercontent.com/8419308/112187404-b072d300-8bc7-11eb-9e9b-7c221c95ada0.png)
![image](https://user-images.githubusercontent.com/8419308/112187603-dac49080-8bc7-11eb-8ab1-4a234c092b75.png)

* In the case where the hint arrows are correctly dismissed in the downstream sim, they aren't restored when pressing the ResetAllButton in the upstream sim:
![image](https://user-images.githubusercontent.com/8419308/112188138-5c1c2300-8bc8-11eb-9150-3d986b037785.png)

**Comment by pixelzoom** [comment]
It's amazing how something as simple as hint arrows has become so mind-bogglingly for PhET-iO.

**Comment by pixelzoom** [comment]
@arouinfar We need to have a design chat about how hint arrows should behave in the Preview sim.  So far we have consider either (a) instrument `visibleProperty` for the hint arrow nodes, or (b) add a new instrumented Property, something like `hintArrowsVisibleProperty`, that is responsible for the state.  In both of those cases, if the molecule has been changed in any way before pressing "Preview Sims", the hint arrows will NEVER appear in the Preview -- not when it is initialized, and not when you press Reset All.   So the design question is:  When should the hint arrows be shown? Only when the molecule is in its default initial state?  Or in ANY initial state, like the initial state of the Preview sim?

**Comment by arouinfar** [comment]
> So far we have considered either (a) instrument visibleProperty for the hint arrow nodes, or (b) add a new instrumented Property, something like hintArrowsVisibleProperty, that is responsible for the state. 

From a design perspective, (a) seems a bit cleaner, but I think you should go with whatever makes more sense from an implementation perspective. However, I do think that the visibleProperty of the individual hint arrows should be read-only. The model should decide when the arrows are visible, otherwise, I think things could get really weird if clients start controlling the visibility of individual arrows.

> if the molecule has been changed in any way before pressing "Preview Sims", the hint arrows will NEVER appear in the Preview -- not when it is initialized, and not when you press Reset All.

@pixelzoom I completely forgot that when a sim is previewed in studio the state restored by the ResetAllButton is no longer the default initial state, but rather the customized initial state. The behavior you describe here makes sense to me. I do not think we need to be worried about the hint arrows in this case. 

> When should the hint arrows be shown? Only when the molecule is in its DEFAULT initial state? Or when the molecule is in ANY initial state, like the initial state of the Preview sim?

@pixelzoom I would go with just the DEFAULT initial state of the molecule. I think things could get complicated if we start trying to display hint arrows on any initial state. If the hint arrows were already dismissed, it would look weird for them to reappear. We don't know that a client would even want the hint arrows in this case, and I don't want to bother with trying to come up with some solution for how they can opt-in/out.

That said, I still think the behavior I saw in the state wrapper is buggy, but that seems like a somewhat different situation than what we were seeing when the sim is Previewed in studio.

**Comment by pixelzoom** [comment]
> @pixelzoom I would go with just the DEFAULT initial state of the molecule. I think things could get complicated if we start trying to display hint arrows on any initial state. ...

Indeed, very complicated.  So I'll proceed under the assumption that hint arrows are show only in the DEFAULT initial state.

**Comment by pixelzoom** [comment]
I used the approach of instrumenting each hint arrow Node, identified as (a) in https://github.com/phetsims/molecule-polarity/issues/106#issuecomment-806069428.

The `moleculeNode` branch of the Studio tree looks like this for the _Two Atoms_ screen:

<img width="267" alt="screenshot_934" src="https://user-images.githubusercontent.com/3046552/112396980-cadfa600-8cc6-11eb-8d7c-f7f5b0646be9.png">

... and this for the _Three Atoms_ screen:

<img width="229" alt="screenshot_935" src="https://user-images.githubusercontent.com/3046552/112397000-d29f4a80-8cc6-11eb-809c-a9000259d729.png">

`hintArrowsNode.visibleProperty` is writeable, and can be used to permanently hide the hint arrows.  It's documentation says: "Set this element to false to permanently hide hint arrows."

`hintArrow*Node.visibleProperty` (for each individual arrow) is read-only. The state of these elements will be saved and restored in the Preview sim.

@arouinfar please review in master.  If it looks OK, please leave the issue open, and change the label to "fixed-awaiting-deploy".

**Comment by arouinfar** [comment]
@pixelzoom the tree structure looks good, as does the behavior when pressing "Preview Sim" in studio and in the downstream sim in the state wrapper. The hint arrows are still correctly disappearing when the corresponding inputEnabledProperty is false too.

**Comment by pixelzoom** [comment]
To verify this issue in 1.1.0-rc.2:

* Verify that the Studio tree looks like what is shown in https://github.com/phetsims/molecule-polarity/issues/106#issuecomment-806251518.
* Verify that setting `hintArrowsNode.visibleProperty` to `false` permanently hides the hint arrows. Test for both screens.
* Verify that if the Preview sim is started when the hint arrows are visible in Studio: the hint arrows are visible when the Preview starts, the hint arrows disappear when you interact with the molecule, and the hint arrows return when you press Reset All.
* Verify that if the Preview sim is started when the hint arrows are NOT visible in Studio: the hint arrows are NOT visible when the Preview starts, and the hint arrows DO NOT return when you press Reset All.

It is sufficient to verify this on 1 platform.

**Comment by DevonQui** [comment]
In Studio, I looked through the tree of both the Two Atoms and Three Atoms screens and the tree for moleculeNode doesn't match what was desired. There are multiple things missing from both versions of the moleculeNode tree. I'll keep searching around to see if they're located somewhere else but I can't locate the missing elements at the moment.
<img width="307" alt="Screen Shot 2021-03-29 at 1 12 17 PM" src="https://user-images.githubusercontent.com/72042459/112888661-e1547b80-9091-11eb-8c63-77c4293573a3.png">

**Comment by DevonQui** [comment]
Verified this on Mac and everything looks fine.
