### ISSUE TITLE
Unable to save to localfile

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-polarity#108]
For https://github.com/phetsims/QA/issues/627
When trying to test recording and playback, I was unable to save the recording. This means I am not able to use it to test if events were captured correctly. If I am doing something wrong, please let me know so I can fix it. This was seen on Win 10 Chrome.
<img width="956" alt="unabletosavelocalfile" src="https://user-images.githubusercontent.com/41024075/112226991-8e437a00-8bf4-11eb-9f24-ab5c4a473973.png">

**Comment by pixelzoom** [comment]
I'm not familiar with this aspect of PhET-iO, so we'll need to ask @zepumph for assistance.

**Comment by KatieWoe** [comment]
I saw this bug when using the link given in the rc: `https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60&localFile`
When using: `https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet-io/wrappers/record/?localFile`, which is the normal type of link, I was able to save and playback just fine. Hope that helps.

**Comment by pixelzoom** [comment]
So maybe the link in the QA issue is incorrect?  I don't know...

**Comment by KatieWoe** [comment]
I tested the link again on MacOS 11 Safari and it did work. I'm really not sure why. If anyone needs to pair for this, let me know.

**Comment by pixelzoom** [comment]
Slack phet-io channel:

Chris Malley  12:16 PM
QA is unable to test localfile record/playback in the latest Molecule Polarity RC. This is of primary importance to Ido’s study, and needs to be resolved asap. Can someone from PhET-iO team please assist? https://github.com/phetsims/molecule-polarity/issues/108

**Comment by KatieWoe** [comment]
I went back to Win 10 Chrome and I was able to get it to work. I think I've discovered the issue. If the console is opened in the login screen, saving will work. If you open the console when the sim is visible, after you've entered the passcode, this error occurs. This seems similar to a known issue. I'll look for it and link here.

**Comment by zepumph** [comment]
@KatieWoe, in the above screen shot, you are in the "sim" context for the console. This occurs when you open the console by trying to "inspect" something that is in the sim frame. Please click on the red select box that says "sim", and choose the "top" (at the top) selection, which will put you in the record wrapper context frame. That is where the global function 'saveLogToFile' is located, not in the sim iframe.

**Comment by KatieWoe** [comment]
Ok, right. I think I remember this from an earlier discussion. Sorry about this. In that case this can probably be closed.

**Comment by zepumph** [comment]
No worries! Could you please update the QA book to include this, it is totally not something that is obvious unless you are looking for it or used to it. Then I'm fine closing this as well.

**Comment by pixelzoom** [comment]
@KatieWoe said:
> ... In that case this can probably be closed.

If you have confirmed that you can save to localfile, then feel free to close.
