### ISSUE TITLE
Update credits for 1.1 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#109]
@KatieWoe let me know who I should add to the QA credits.  The current credits are:

```
    qualityAssurance: 'Steele Dalton, Alex Dornan, Ethan Johnson'
```

**Comment by KatieWoe** [comment]
Just myself for this one

**Comment by pixelzoom** [comment]
@KatieWoe I see your name as both "Kathryn Woessner" (36x) and "Katie Woessner" (15x) in credits.  Do you have a preference?  Do you want to standardize?

**Comment by pixelzoom** [comment]
Slack:


Kathryn Woessner:house_with_garden:  9:15 AM
I generally go with Kathryn as my professional name, but I don't really mind either way. It seems like more trouble than it's worth to change the other instances.






Chris Malley  9:16 AM
It’s pretty easy to change in master. And it will prevent confusion like I’m having :)   So OK to change to “Kathryn” throughout all credits?

Kathryn Woessner:house_with_garden:  9:16 AM
Sounds good :+1:

**Comment by pixelzoom** [comment]
"Kathryn Woessner" added to credits in master and 1.1 branches.

**Comment by pixelzoom** [comment]
"Katie Woessner" has been changed to "Kathryn Woessner" throughout QA credits in master.

**Comment by pixelzoom** [comment]
I also noticed that @arouinfar is not included in the credits. She asked to be added to the "Team" section.   Done in the above commits to master and 1.1 branches.

**Comment by pixelzoom** [comment]
Here's how the credits will appear for 1.1:

<img width="608" alt="screenshot_937" src="https://user-images.githubusercontent.com/3046552/112500418-f9ed2a80-8d4d-11eb-99cd-adcb10185b69.png">

**Comment by pixelzoom** [comment]
To verify this issue, open the About dialog in 1.1.0-rc.2.  Verify that the credits are as desired. Specifically verify that "Kathryn Woessner" was added to QA, and "Amy Rouinfar" was added to Team.

**Comment by KatieWoe** [comment]
This change was made. Devon Quispe was involved in this spot-check, so should probably be added. That change probably doesn't need a spot check.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. I will add Devon Quispe to the QA credits in the main and 1.1 branches. But I'm not going to generate a new RC for that change.
