### ISSUE TITLE
Which branch should be used for the next production release?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#112]
PhET is about to wrap up a 1.1 RC release for a research collaborator, see #87.   

Since the PhET-iO instrumentation for this sim is in good shape, there has been talk of moving forward with a production release.  That release could be a continution of the 1.1 branch, or it could be based on a new 1.2 branch (created from master).  

My recommendation is use a new 1.2 branch. It is the lower-cost option and will result in a superior production release.  My reasoning is:
* PhET has a minimal investment in the 1.1 branch. It has received only RC-research testing. So there's little to be gained by continuing the 1.1 branch.
* Given the other priorities that I'm aware of, I doubt that a production release will occur in the next few weeks, maybe not even in 2021 Q2.  That means maintaining the 1.1 branch for a significant period of time.
* Maintaining the 1.1 branch is a significant cost. As the master branch diverges, changes need to be patched into the 1.1 branch. That cost is already being incurred (see for example #110 and #111). As time goes by, that cost increases.  And that cost will quickly eclipse anything that was gained by using the 1.1 branch.
* The "featured" part of PhET-iO design has not been done, see #104.  The overrides.js file will certainly change, as could sim code and common code. Patching those changes into the 1.1 branch will take time, and will become more complicated as time goes by.

This is important to decide now because master has already diverged, and PhET is already incurring the cost of tracking potential patches for the 1.1 branch (e.g. see #110 and #111).

@arouinfar @kathy-phet How would you like to proceed for the production release?  And if you have any thoughts on when that might be scheduled, that would be helpful.

**Comment by arouinfar** [comment]
Thanks for writing this up @pixelzoom. Another thing to consider is that studio save/load is possibly still buggy (currently being tested for GAO release), and we would definitely want that feature in the next production release. All signs point to creating the 1.2 branch when the time comes.

**Comment by kathy-phet** [comment]
I agree, go with 1.2 as a new release from master.

**Comment by pixelzoom** [comment]
Great, I'll close this issue, and proceed with cleaning up loose ends.
