### ISSUE TITLE
Molecule Polarity 1.2 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#114]
From 4/2/21 Q2 planning meeting...

* brands=phet,phet-io
* new 1.2 release branch
* full QA process (dev + RC)
* publish by 6/30/21

@arouinfar @kathy-phet FYI.

**Comment by arouinfar** [comment]
@pixelzoom I've finished up the phetioFeatured overrides and the client guides. As far as I know, there aren't any sim-specific issues blocking this sim from going to QA.

**Comment by pixelzoom** [comment]
Thanks for the update @arouinfar.   I agree, there are no sim-specific issues blocking QA.  To meet the 6/30/21 publication milestone, QA for this sim should start sometime the first week of June.  Assigning to @kathy-phet for scheduling.  When you're ready to start QA, please assign this issue back to me with instructions.

**Comment by pixelzoom** [comment]
We're now 1 week past the milestone. Assigning to @kathy-phet to revise.  Feel free to assign back to me when you're ready to proceed with publishing this release.

**Comment by pixelzoom** [comment]
Dev test published 7/26/2021:
* https://github.com/phetsims/qa/issues/680

**Comment by pixelzoom** [comment]
8/4/2021:
* 1.2.0-rc.1 published for full RC test, https://github.com/phetsims/qa/issues/688

**Comment by pixelzoom** [comment]
8/16/2021: Molecule Polarity 1.2.0 was deployed.

https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity_en.html
https://phet-io.colorado.edu/sims/molecule-polarity/1.2

Extra steps identifed by `grunt production`:

> PhET-iO deploys involve a couple of extra steps after production. Please ensure the following are accomplished:
> 1. Make sure the sim is listed in perennial/data/phet-io-api-stable, if it has had a designed production release, and update the checked in API file to match the published version.

Confirmed, it's listed.

> 2. Create an issue in the phet-io repo and assign to @kathy-phet to update the main "PhET-iO Simulations" spreadsheet from this new publication. (https://docs.google.com/spreadsheets/d/18_QNGuVtYtxOEKG9xRBs_PSQpyvzySF1Gk5puR-5Fv4/edit#gid=1881767354)

See https://github.com/phetsims/phet-io/issues/1813

> 3. If you are delivering this version to a research partner, update partners.md (phet-io/doc/partners.md) to show this delivery. (Read the intro of the document to make sure that you format the entry correctly.)

I don't know what to do here.  Tracking in https://github.com/phetsims/phet-io/issues/1811.

> 4. If this is a version that will be used with students, then make sure to remove the password protection, see https://github.com/phetsims/phet-io/blob/master/doc/phet-io-security.md for details. 

I don't know what to do here.  Tracking in https://github.com/phetsims/phet-io/issues/1812.
