### ISSUE TITLE
Uninstrument bondDipolesCheckbox.labelNode.labelIcon

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-polarity#116]
Discovered during #104 

The icon next to the "Bond Dipole" checkbox is instrumented, though the same was not done for the "Molecular Dipole" checkbox. For consistency, the icons should be treated the same. @kathy-phet and I didn't see any particular reason why the icon needs to be instrumented separately from the checkbox, so we'd like to uninstrument `moleculePolarity.*Screen.view.controlPanel.viewControls.bondDipoleCheckbox.labelNode.labelIcon`.

**Comment by pixelzoom** [comment]
Done, @arouinfar please verify in master.  If it looks OK, you can close this issue.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom
