### ISSUE TITLE
Update Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-polarity#117]
Related to #114 

The Teacher Tips should be updated for the 1.2 version. Updates include:

- [x] Use modern template
- [x] Add query parameter table: `screens`, `supportsPanAndZoom`, `dipoleDirection`
- [x] When the E-Field is turned on, the molecule's angular velocity is proportional to the molecular dipole moment. If the molecular dipole is tiny (but non-zero) it can rotate over several minutes, see #128.

**Comment by pixelzoom** [comment]
@arouinfar Molecule Polarity 1.2.0 has been published, so you can proceed with this issue.

**Comment by arouinfar** [comment]
For some reason, I was thinking this issue was blocked until 1.3 was published, but I was very wrong. Teacher Tips have been updated and uploaded to the website. Closing.
