### ISSUE TITLE
Update credits for 1.2 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#120]
Current credits are shown below. 

<img width="646" alt="screenshot_1094" src="https://user-images.githubusercontent.com/3046552/127199053-4bb0841b-b592-44ff-8553-eed73a0f8833.png">

**Comment by pixelzoom** [comment]
@KatieWoe When you've completed dev test https://github.com/phetsims/qa/issues/680, please let me know who you'd like added to the QA credits.  It will be more efficient if I can do this in master _before_ creating the 1.2 release branch. Thanks!

**Comment by KatieWoe** [comment]
Emily Miller, Nancy Salpepi, Brooklyn Lash, Devon Quispe, and myself worked on the dev version.

**Comment by pixelzoom** [comment]
QA credits have been updated in master, see screenshot below. 

I'll leave this open in case we need to make additional changes during the RC process.

<img width="636" alt="screenshot_1123" src="https://user-images.githubusercontent.com/3046552/128243905-8b3ff061-c34e-4722-bb4d-1441a154750b.png">

**Comment by KatieWoe** [comment]
Looks good

**Comment by pixelzoom** [comment]
👍🏻 Closing.
