### ISSUE TITLE
Client Requests guide leaves out hiding Real Molecules navbar icon

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-polarity#124]
**Device**
Dell
**OS**
Win 10
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/680. The client guide has a section for hiding everything on the nav bar. However, the guide only provides info for the first two screen icons, not the third. While the third screen is irrelevant, the icon should still be hideable.
**Visuals**
<img width="724" alt="hidethirdscreen" src="https://user-images.githubusercontent.com/41024075/128063255-8834c9d5-836b-429b-ad2b-d6ff5430477d.png">

**Comment by pixelzoom** [comment]
This is in Client Requests, which is one of 3 possible "client guides" (the other 2 being PhET-iO Guide and Migration Guide). That said... 

I realize that this section is responding to a specific client request.  But honestly, I think this section should NOT enumerate these "not recommended" Properties.  Instead, shorten this section to:

> **Hide each item in the navigation bar**
> The PhET-iO logo cannot be hidden, only disabled using `moleculePolarity.general.view.navigationBar.phetButton.enabledProperty`.
> 
> To limit which screens a student has access to, do not hide or disable screen icons in the navigation bar. Use the screens query parameter (see the PhET-iO Guide).

But this is @arouinfar's call, so unassigning myself.

**Comment by pixelzoom** [comment]
Raising priority to high. This is a dev test, the dev testing is wrapping up, and it's important to create the release branch ASAP after creating the dev test.

**Comment by arouinfar** [comment]
My understanding is that #88 should have applied to all PhET-iO versions, and the Real Molecules screen should be hidden in phet-io-brand. That is the reason I don't explicitly mention the Real Molecules screen.

> I realize that this section is responding to a specific client request. But honestly, I think this section should NOT enumerate these "not recommended" Properties. Instead, shorten this section to:

This request applies to all multi-screen sims and is included in the template. The [template was updated](https://github.com/phetsims/phet-io-client-guides/commit/6d9aa7c68929c30b8dc1d916f0df118bc0a143f7#diff-e9c288ac886241488fd437e35e252b11e9938f97b2c27ddba036d8aaea96d701) to include the "not recommended" language during a meeting with @kathy-phet @amanda-phet and myself. I do, however, prefer @pixelzoom's suggestion.

I am fine with updating this sim and the template. However, we'll need to decide if this should be propagated to all sims, including recent publications like natural-selection, ph-scale, and gravity-and-orbits. The client requests docs do not include the "not recommend" language (predate the updated template), but the screen icons are still enumerated. My vote would be to leave published sims as-is and just make the change for future publications from master. What do you think @pixelzoom?

**Comment by arouinfar** [comment]
> My understanding is that #88 should have applied to all PhET-iO versions, and the Real Molecules screen should be hidden in phet-io-brand. That is the reason I don't explicitly mention the Real Molecules screen.

I'll retract this statement. My concern was that we would be revealing unfinished/unreviewed instrumentation, but this was addressed by hiding most elements in the tree for the Real Molecules screen in #123.

**Comment by pixelzoom** [comment]
That's most consistent with prior precedent - PhET typically does not omit features or screens from PhET-iO versions.  And omitting screens is the job of the `?screens` query parameters.  Should something more specific about `?screens` and the Real Molecules screen be added to one of the client guides?

**Comment by pixelzoom** [comment]
Back to @arouinfar

- [ ] What do you think of my proposal in https://github.com/phetsims/molecule-polarity/issues/124#issuecomment-892057458? 

- [ ] If you're still going to mention `visibleProperty` for navbar buttons, do you want to add `realMoleculesScreenButton.visibleProperty`, as @KatieWoe notes is missing? 

- [ ] Should something more specific about `?screens` and the Real Molecules screen be added to one of the client guides?

**Comment by pixelzoom** [comment]
In a Zoom call with @arouinfar, she mentioned that she has completed work for this issue, but hadn't had a chance to comment yet.    I verified her changes, and this issue can be closed.
