### ISSUE TITLE
Should Client Requests guide mention electronegativityProperty?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-polarity#125]
For https://github.com/phetsims/qa/issues/680. In the client guide, there is a section that instructs the client to change an atoms electronegativity using electronegativityProperty and it links to those properties. However, these properties don't seem to allow user control in studio. Should they still be mentioned?
<img width="689" alt="property" src="https://user-images.githubusercontent.com/41024075/128080468-c2b2bea3-a69d-4ba7-973f-5870f1842426.png">
<img width="677" alt="electronegative" src="https://user-images.githubusercontent.com/41024075/128080469-15203ab6-97dc-4dd7-83a6-0e2bea261e1d.png">

**Comment by pixelzoom** [comment]
This is in the Client Requests guide. I'll change the title of this issue.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/molecule-polarity/issues/94,  @arouinfar requested that the electronegativity sliders snap to 0.2 intervals when released.  Studio's slider has no support for this type of snapping, so the associated Property has metadata  `phetioStudioControl: false` in Atom.js:

```js
    // @public
    this.electronegativityProperty = new NumberProperty( options.electronegativity, {
      range: MPConstants.ELECTRONEGATIVITY_RANGE,
      tandem: options.tandem.createTandem( 'electronegativityProperty' ),
      phetioStudioControl: false // because not continuous, see https://github.com/phetsims/molecule-polarity/issues/94
    } );
```

Options, from least-to-most cost:

(1) Leave it as is - no setting of `electronegativityProperty`, and fix the Client Requests guide.

(2) Remove `phetioStudioControl: false` and let the client set `electronegativityProperty` to continuous values in the range [2,4].

(3) Add `validValues` option to `electronegativityProperty`, to enumerate the 11 possible values at 0.2 intervals in the range [2,4].  As will all NumberProperty instances, this will result in a radio button in Studio for each possible value, NOT a slider. 

@arouinfar your preference?

**Comment by pixelzoom** [comment]
Here's what option (3) would look like in Studio.  Not very pretty, but it does the job.

<img width="1043" alt="screenshot_1121" src="https://user-images.githubusercontent.com/3046552/128086718-f7b3ab21-96b7-4669-98fc-5840857e39cc.png">

**Comment by pixelzoom** [comment]
My recommendation is option (2).

Here's option (2) in Studio.  `electronegativityProperty` gets a continouos slider.  Yes, the instructional desiger can set to values that are not 0.2 intervals.  But so can a programmer using the PhET-iO API.  And if they want a 0.2 interval, use the slider in the sim -- and note that in the Client Requests guides.  

<img width="1042" alt="screenshot_1122" src="https://user-images.githubusercontent.com/3046552/128087267-c34330c7-56ed-44b3-8681-5e1d6ae73d09.png">

**Comment by pixelzoom** [comment]
Raising priority to high. This is a dev test, the dev testing is wrapping up, and it's important to create the release branch ASAP after creating the dev test.

**Comment by arouinfar** [comment]
I think the issue here is a misinterpretation. The client-requests doc tells people to:

> Set the electronegativity with the sliders in the simulation in PhET-iO Studio or via the corresponding `electronegativityProperty.`

Looks this is interpreted as using the slider in the Studio interface, but its intent is to tell folks to use the slider in the sim itself. I'll drop the "in PhET-iO Studio" so it simply reads:

> Set the electronegativity with the sliders in the simulation or via the corresponding `electronegativityProperty.`

**Comment by arouinfar** [comment]
Done in the above commit, back to @pixelzoom.

**Comment by arouinfar** [comment]
@KatieWoe we often remove sliders from the Studio interface because they cannot snap in intervals as is done in the simulation. The property is not read-only so a client can still set the value of the `electronegativityProperty` using an API, which is why it's mentioned in the client requests.

**Comment by pixelzoom** [comment]
Looks good to me.

@KatieWoe please review in master. Please close if it's OK.

**Comment by KatieWoe** [comment]
Looks good in master
