### ISSUE TITLE
C atom listed twice in Client Requests guide

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-polarity#126]
For https://github.com/phetsims/qa/issues/680. Under "Preset the electronegativity and prevent further editing" the element `moleculePolarity.threeAtomsScreen.view.electronegativityPanels.atomCElectronegativityPanel.slider.visibleProperty
` is listed twice, and `moleculePolarity.threeAtomsScreen.view.electronegativityPanels.atomBElectronegativityPanel.slider.visibleProperty` is not listed.
<img width="780" alt="clistedtwice" src="https://user-images.githubusercontent.com/41024075/128082877-02d278aa-9334-4b25-86aa-891855faca7c.png">

**Comment by pixelzoom** [comment]
This one is up to @arouinfar, looks like a copy-paste error.

**Comment by pixelzoom** [comment]
Raising priority to high. This is a dev test, the dev testing is wrapping up, and it's important to create the release branch ASAP after creating the dev test.

**Comment by arouinfar** [comment]
Good catch @KatieWoe. Fixed in the above commit @pixelzoom.

**Comment by pixelzoom** [comment]
Looks good to me.

@KatieWoe please review in master. Please close if it looks OK.

**Comment by KatieWoe** [comment]
Looks good in master
