### ISSUE TITLE
allowLinks parameter does not disable all links

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-polarity#127]
For https://github.com/phetsims/qa/issues/680.
The link to the legacy version of the sim in the third screen is not disabled by `?allowLinks=false`
![allowlinksbug](https://user-images.githubusercontent.com/41024075/128094161-046d062f-f836-4634-9118-7c163a693c41.gif)

**Comment by pixelzoom** [comment]
Checking `?allowLinks` is apparently not supported by any common code, and must be done by the sim.  Fixed in master. @KatieWoe please verify, please close if it looks OK.

**Comment by KatieWoe** [comment]
Looks good in master
