### ISSUE TITLE
Molecule Polarity - Publish 1.3 with PhET-iO Upgrades

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/molecule-polarity#137]
As part of the "batch release" milestone https://github.com/orgs/phetsims/projects/44, publish Molecule Polarity, for brands=phet,phet-io.

**Comment by pixelzoom** [comment]
Unassigning until this becomes a priority.

**Comment by pixelzoom** [comment]
12/22/2022 phet-io meeting:   

This is coming up for publication, so self assigning.

**Comment by pixelzoom** [comment]
Molecule Polarity is not currently a publication priority, so unassigning.

**Comment by pixelzoom** [comment]
Getting this sim into dev testing is on the worklist for the May 18 - June 7 iteratig on.  There is one remaining issue blocking that: https://github.com/phetsims/molecule-polarity/issues/141.

**Comment by pixelzoom** [comment]
Getting this sim into dev testing is on the worklist for the May 18 - June 7 iteratig on.  There is one remaining issue blocking that: https://github.com/phetsims/molecule-polarity/issues/141. @zepumph FYI.

**Comment by pixelzoom** [comment]
6/3/23 created dev-test issue, will deploy dev version when QA is ready to being:
* https://github.com/phetsims/qa/issues/952

**Comment by pixelzoom** [comment]
Dev testing has been completed. There were 0 general issues, 1 sim-specific PhET-iO issue, 3 common-code PhET-iO issues.

Creation the 1.3 release branch (and start of RC testing) is blocked pending resolution of:
* https://github.com/phetsims/phet-io-wrappers/issues/521
* https://github.com/phetsims/studio/issues/305

FYI @arouinfar @kathy-phet @samreid @zepumph

**Comment by pixelzoom** [comment]
6/22/23 second RC test deployed:
* https://github.com/phetsims/qa/issues/960

**Comment by pixelzoom** [comment]
1.3.0 was published on 6/22/23.

Closing.
