### ISSUE TITLE
Update QA credits for 1.3 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#138]
Update QA credits for 1.3 release, https://github.com/phetsims/molecule-polarity/issues/137.

**Comment by pixelzoom** [comment]
For dev test https://github.com/phetsims/qa/issues/952#issuecomment-1585004913, @Nancy-Salpepi said:
> Jaron Droder should be added to QA credits.

**Comment by Nancy-Salpepi** [comment]
Please add Clifford Hardin.

**Comment by Nancy-Salpepi** [comment]
Everyone has been added. Closing.
