### ISSUE TITLE
Fold Options into Preferences

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#139]
Related to https://github.com/phetsims/joist/issues/837 ...   

- [x] Add Preferences dialog
- [x] Fold the Options dialog into the Preferences dialog
- [x] Rename things accordingly (MPOptionsNode, MPGlobalOptions, associated tandems)
- [ ] Revise the PhET-iO API, have it approved by @arouinfar 

Some of this has already been handled by @zepumph in https://github.com/phetsims/joist/issues/837.

**Comment by pixelzoom** [comment]
This is ready for PhET-iO design review by @arouinfar.  

Following the same conventions used in Geometric Optics (see https://github.com/phetsims/geometric-optics/issues/440#issuecomment-1226228772) here's a summary of the changes:

* Properties related to Options were formerly under `global.model`.  They are now under `global.model.preferences`.

* `geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsMenuItem` no longer exists, because there is no Options menu item in the PhET menu.

* `geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule` no longer exists, because there is no Options dialog. Controls that appeared in the Options dialog were moved to the General tab of the Preferences dialog.

* Controls that were added to the General tab of the Preferences dialog now appear under `geometricOptics.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.generalPreferencesPanel.simPreferences` .  The `simPreferences` naming convention was chosen in https://github.com/phetsims/joist/issues/837#issuecomment-1224743329. Feel free to recommend a different convention, since that's what this review is about.

**Comment by arouinfar** [comment]
Reviewed with @matthew-blackman and everything looks good @pixelzoom. Closing.
