### ISSUE TITLE
Add support for dynamic locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#140]
... similar to what was done in https://github.com/phetsims/natural-selection/issues/319.

**Comment by pixelzoom** [comment]
This sim is next on the priority list, so labeling as high.

**Comment by pixelzoom** [comment]
I published [1.3.0-dev.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.0-dev.1) for `brands=phet,phet-io` as a baseline before starting this work.

**Comment by pixelzoom** [comment]
Good progress on this today.  Remaining work is indicated by TODO comments in the code.

**Comment by pixelzoom** [comment]
@arouinfar this is ready for review.  Unlike Natural Selection and Geometric, I did not instrument additional Text/RichText nodes, and all translated StringProperties are therefore not discoverable by inspecting Text/RichText elements in Studio.  If you want additional Text/RichText instrumented, please identify them.

**Comment by pixelzoom** [comment]
Oops, I still have some layout work to do here. Assigning back to me.

**Comment by pixelzoom** [comment]
OK, ready for review.

**Comment by arouinfar** [comment]
@pixelzoom I reviewed the tree in master, and things are looking good. I see linked properties back to `StringProperties` where I would expect, and the dynamic layout seems good.

The only odd case I found was the screen icons. The atom name can spill outside of the bounds in the iconic version, but that doesn't happen to the atoms in the play area.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/8419308/189770249-c3e0a51f-b746-4162-9d30-07bafeab0ba8.png">

**Comment by pixelzoom** [comment]
Fixed, back to @arouinfar to verify.  Feel free to close if it looks OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good!

<img width="276" alt="image" src="https://user-images.githubusercontent.com/8419308/189949258-02af6e41-a814-43ce-bf1c-78557f40f5f6.png">

**Comment by pixelzoom** [comment]
Commits above were incorrectly tagged for this issue, and should have been tagged for https://github.com/phetsims/molecule-polarity/issues/141.
