### ISSUE TITLE
PhET-iO design review for 1.3 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#142]
#141 (add support for dynamic locale) will certainly result in many API changes, and there have been many common-code API changes and additions.  So this sim will require a full design review of the PhET-iO API.

**Comment by pixelzoom** [comment]
At 9/1/2022 design meeting, @kathy-phet said that design review should happen before migration rules #141.  So this issue is ready for review.

**Comment by arouinfar** [comment]
I completed the tree review, and I didn't find any issues other than the needed tweaks to the `phetioFeatured` overrides and examples.md (which are tracked in the tagged issues above). Closing.
