### ISSUE TITLE
Missing PhET-iO elements in Preferences dialog under `simPreferences` 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#144]
Related to https://github.com/phetsims/molecule-polarity/issues/140 (add support for dynamic locale), I'm running into a problem with the Preferences dialog in Studio.   The sim adds one subpanel that contains a title ("Dipole direction") and a radio button group:

<img width="387" alt="screenshot_1847" src="https://user-images.githubusercontent.com/3046552/187579154-8555f6f8-991e-4da3-8a2c-43cd3b657d1b.png">

The subpanel is implemented in DipoleDirectionControl.js, the radio button group in DipoleDirectionRadioButtonGroup.js.

After opening the Preferences dialog, under `moleculePolarity.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.generalPreferencesPanel.simPreferences` you'll see this subtree:

<img width="285" alt="screenshot_1850" src="https://user-images.githubusercontent.com/3046552/187580544-b7630b39-3762-45f2-95bf-ecb849603956.png">

Four problems, all in DipoleDirectionRadioButtonGroup.js:

(1) DerivedProperty `negativeToPositiveRadioButton.negativeToPositiveStringProperty` is missing from the tree.

(2) `negativeToPositiveRadioButton.labelText` is missing child `textProperty` that links to `negativeToPositiveRadioButton.negativeToPositiveStringProperty`.

(3) Similar to (1), DerivedProperty `positiveToNegativeRadioButton.positiveToNegativeStringProperty` is missing from the tree.

(4) Similar to (2), `positiveToNegativeRadioButton.labelText` is missing child `textProperty` that links to `positiveToNegativeRadioButton.positiveToNegativeStringProperty`.

Am I hitting some limitation/problem with PhetioCapsule?

**Comment by pixelzoom** [comment]
I thought the problem might be caused by instantiating DerivedProperty inside of a dynamic component. So I temporarily moved `negativeToPositiveStringProperty` and  `positiveToNegativeStringProperty` to MPConstants.  The behavior was unchanged.

**Comment by samreid** [comment]
Fixed in the commit, please review.  Also, should we convert StringUtils to TypeScript and ban certain keys/value types?  But perhaps this will be better addressed in PatternStringProperty which @jonathanolson is working on.

**Comment by pixelzoom** [comment]
> Fixed in the commit, please review. 

Oh duh, options in the wrong place... and thanks.  

> Also, should we convert StringUtils to TypeScript and ban certain keys/value types?

I don't think that's necessary. If Molecule Polarity had been in TypeScript (it is now), this would have been caught.

Closing.
