### ISSUE TITLE
Horizontal separators in the control panel do not resize when locale is changed. 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#147]
Related to #140 ...

Horizontal separators in the control panel do not resize when locale is changed.  For example:

<img width="349" alt="screenshot_1857" src="https://user-images.githubusercontent.com/3046552/189449600-cba3ef2f-9849-4476-a563-2fa972bbf19c.png">

**Comment by pixelzoom** [comment]
Addressed in the above commits.

But this required a PhET-iO API change because of https://github.com/phetsims/scenery/issues/1448.  When implementing Scenery Layout, @jonathanolson chose to rename "separators" to "dividers".  I see no advantage to changing the terminology from "separator" to "divider".  And there's a big disadvantage: any sim (like this one) that has a "separator" element needs to be renamed to "divider", changing the PhET-iO API.    And in this sim, that also required manually editing the overrides.js file, because the separator is featured. 

@arouinfar please review the API change. 


@kathy-phet FYI.

**Comment by arouinfar** [comment]
@pixelzoom the behavior looks good in master and I don't see anything technically wrong with the change to `divider`. However, my preference is that we stick with `separator` so we should wait until https://github.com/phetsims/scenery/issues/1448 is settled before closing this out.

**Comment by pixelzoom** [comment]
"Separator" terminology was restored in https://github.com/phetsims/scenery/issues/1448, and "separator" tandem names were restored in the above commit.  

@arouinfar please review, close if OK.  You can verify for searching for "divider" and "separator" in Studio.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom
