### ISSUE TITLE
Link to locale-specific Java version

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#151]
@DianaTavares reported in Slack#general:

> Hi! I am in a teacher's presentation on how they are planning to use PhET sims. I realize that the sim "Molecule Polarity", in the Real Molecules, suggests using the Java sim,  but the link goes to the English version. I thought that I could change the link in the Translation Tool, but no, the link is not a string that can be changed. Is possible that the link to the java sims go to the same local that the HTML5? or probably add to the dialog text in the HTML5 sim to look in the translations for the correct local.

![image](https://user-images.githubusercontent.com/3046552/209178395-ef5d3ed1-97e3-4056-8ff4-1f1c28d3a82a.png)

**Comment by pixelzoom** [comment]
Links are typically not translatable, it's a security issue.

`phet.chipper.queryParameters.locale` gives us runtime locale of the sim. So I think the general form of the link could be changed to this, but I'm not 100% certain:

```
https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity_${phet.chipper.queryParameters.locale}.html
```

@arouinfar thoughts? Should we spend time on this?

**Comment by pixelzoom** [comment]
Ah... But since locale can be changed dynamically, the link will also need to change dynamically.  So something like this (untested):

```typescript
const linkStringProperty = new DerivedProperty( [ localeProperty ], locale => 
  `https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity_${locale}.html`
);
```

**Comment by pixelzoom** [comment]
But wait, there's more complication... 

`https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity_${locale}.html` is the link to the HTML5 version, not the legacy version.  

When I go to the legacy page at https://phet.colorado.edu/en/simulation/legacy/molecule-polarity, there's no a specific URL per locale. You have to select the Translation tab, then decided whether to press the CheerpJ or Java button.

So yes, I can figure out what the locale is, and I can even make that dynamic.  But I don't know what the URL should be.

**Comment by pixelzoom** [comment]
I'm confused...

If I go directly to https://phet.colorado.edu/en/simulations/molecule-polarity/translations, it takes me to the HTML5 translations.

If I go first go to https://phet.colorado.edu/en/simulations/legacy/molecule-polarity, then press the Translations tab, it takes me the exact same URL https://phet.colorado.edu/en/simulations/molecule-polarity/translations. 

If then press the browser reload button, I'm still at the same URL, but viewing HTML5 translations.

So there appear to be no direct link to the legacy translations.

**Comment by pixelzoom** [comment]
@mattpen replied in Slack#dev-public:

> Try replacing /legacy/ with /deprecated/
> https://phet.colorado.edu/en/simulations/deprecated/molecule-polarity/translations
>
> I see now that clicking the translation tab even on the deprecated page will remove that path from the URL, I’ll open an issue to fix that
> 
> This is intentionally not published publicly anywhere

**Comment by pixelzoom** [comment]
General form `https://phet.colorado.edu/${locale}/simulations/deprecated/molecule-polarity/translations` does indeed get me to the locale-specific Translations page for `${locale}` .  But if the HTML5 sim is running in a local for which there is no legacy page, then I get a 404 error.  So I think there’s a fundamental problem with linking directly to a locale-specific legacy page.

**Comment by mattpen** [comment]
The link on the TAB on Molecule Polarity's page is [broken](https://github.com/phetsims/website-meteor/issues/508), but this URL should work: https://phet.colorado.edu/en/simulations/legacy/molecule-polarity/translations

Unfortunately, the list of locales supported by the website is never going to be the same as the list of locales for molecule-polarity, so for that link to be localized we'll need to do some kind of checking for support.  We could somehow build in a list of website supported locales, but that would mean we need to maintenance release all sims every time a locale is added to the website.  We could also do an http check for https://phet.colorado.edu/{{locale}}/simulations/legacy/molecule-polarity/translations, then if we get 200 OK show that link and if we get a 404 show the English link.  These both sound like poor solutions.

**Comment by pixelzoom** [comment]
So... Because the HTML5 locale may not exist for the legacy version, the only safe thing to do is send them to the English legacy page.    If we add something to the dialog that tells the user to click the "Translations" button, that's not going to be very effective -- the English page will be showing "Translations", and the dialog text will get translated to something else.

So my recommendation here is to acknoweldge the deficiency of what we currently have, but change nothing.  This message was suppose to be temporary, until the Real Molecules screen was completed. The effort would be better spent completing that screen.

@arouinfar thoughts?

**Comment by arouinfar** [comment]
@mattpen is right. The website (and therefore simulation page) will exist in far fewer languages than either version of the sim ever will. Using something like {{locale}} in the path isn't going to work without an elaborate set of fallbacks, and I don't think it's worth the time.

We could instead link to https://phet.colorado.edu/en/simulations/legacy/molecule-polarity/translations, which seems like an easy change. It has basically no effect on the English-speaking user and it would save a click for people who would need to use a translated version of the sim. @pixelzoom can you update the link?

**Comment by pixelzoom** [comment]
Link updated, see screenshot below.

@arouinfar @DianaTavares please review.

<img width="634" alt="screenshot_2087" src="https://user-images.githubusercontent.com/3046552/209223217-536640c5-6132-4e2c-83d3-efe7931d75ef.png">

**Comment by arouinfar** [comment]
Looks good to me, thanks @pixelzoom!

**Comment by DianaTavares** [comment]
Looks good! Thanks!!
