### ISSUE TITLE
Consider expanding touch areas for checkboxes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-polarity#161]
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.5

**Problem description**
For https://github.com/phetsims/qa/issues/956, the touch/pointer areas for checkboxes are small. It would be easier to select on touch devices if they were the same size as the areas for radio buttons.

**Visuals**

<img width="344" alt="Screenshot 2023-06-16 at 9 55 35 AM" src="https://github.com/phetsims/molecule-polarity/assets/87318828/1b6ea107-740e-4adb-83b4-e6a086b1a926">

<img width="224" alt="Screenshot 2023-06-16 at 10 24 09 AM" src="https://github.com/phetsims/molecule-polarity/assets/87318828/b45e8f3b-f7b1-4f9a-b5c5-016a36bb7b04">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Polarity‬
URL: https://phet-dev.colorado.edu/html/molecule-polarity/1.3.0-rc.1/phet/molecule-polarity_all_phet.html
Version: 1.3.0-rc.1 2023-06-15 19:01:21 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language: en-US
Window: 1566x773
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
I'm guessing that we're not currently using VerticalCheckboxGroup here. I'll investigate.

**Comment by pixelzoom** [comment]
Confirmed that we are not using VerticalCheckboxGroup.

Similar problem in the Three Atoms control panel:

<img width="289" alt="screenshot_2612" src="https://github.com/phetsims/molecule-polarity/assets/3046552/8439fa7a-38fa-4db8-b03f-1e93e29e6882">

And in the Real Molecules control panel, if you run with `?realMolecules`:

<img width="302" alt="screenshot_2613" src="https://github.com/phetsims/molecule-polarity/assets/3046552/faf199d4-ee7b-4210-a51d-6a9d7371adae">

These classes need to use VerticalCheckboxGroup, and renamed:
* TwoAtomsViewControls
* TwoAtomsViewControls
* RealMoleculesViewControls

And I'm going to attempt to do this in a way that does not result in an API change and need for additional migration rules. That is, I will NOT introduce a new `checkboxGroup` element in the Studio tree.

**Comment by pixelzoom** [comment]
I ended up not using VerticalCheckboxGroup -- it does not allow support subclasses of Checkbox, and this sim has many such subclasses.  Instead, I addressed the pointer areas in a new MPCheckbox base class.  See above commit and screenshots below.  @Nancy-Salpepi please review in master. If it's OK, change label to "fix-awaiting-deploy" for review in next RC.

Running with `?showPointerAreas&realMolecules`:

 _Two Atoms_ screen:
<img width="287" alt="screenshot_2616" src="https://github.com/phetsims/molecule-polarity/assets/3046552/5b92ea64-d614-487d-800d-17bcb4b8d2c5">

_Three Atoms_ screen:
<img width="262" alt="screenshot_2615" src="https://github.com/phetsims/molecule-polarity/assets/3046552/a126af1d-cbff-4f43-9c6d-0c3d46cff549">

_Real Molecules_ screen:
<img width="278" alt="screenshot_2614" src="https://github.com/phetsims/molecule-polarity/assets/3046552/4f1f959d-1e1e-446e-bbb4-59a8a6144275">

**Comment by pixelzoom** [comment]
Cherry-picked to the 1.3 branch in the above commit.

**Comment by Nancy-Salpepi** [comment]
Looks good to me.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2
