### ISSUE TITLE
Title of Bond Dipole Checkbox only changes on one screen during Migration

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-polarity#165]
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.5

**Problem description**
For https://github.com/phetsims/qa/issues/956, in the Migration Wrapper: 
If I change the title of the `bondDipoleCheckbox` on the Two Atoms Screen in version 1.2, it doesn't change the title on the Three Atoms Screen in 1.3. However, if I change the titles of `partialChargesCheckbox` and `eFieldControl` on the Two Atoms Screen--those changes are present on both screens after the migration. 

**Steps to reproduce**
1. In the Migration Wrapper on the Two Atoms Screen, change `viewControls.bondDipoleCheckbox.labelNode.labelText.textProperty`
2. Press Migrate Now

**Visuals**
Version 1.2:
<img width="467" alt="Screenshot 2023-06-21 at 10 04 58 PM" src="https://github.com/phetsims/molecule-polarity/assets/87318828/91a7e668-64be-427d-a90a-7604cb3a0c5e">
Version 1.3:
<img width="409" alt="Screenshot 2023-06-21 at 10 05 43 PM" src="https://github.com/phetsims/molecule-polarity/assets/87318828/07aae45b-af53-4a7d-97b2-15d2d48248e3">
<img width="409" alt="Screenshot 2023-06-21 at 10 07 05 PM" src="https://github.com/phetsims/molecule-polarity/assets/87318828/4ed5e1c8-9531-4aea-b252-cb4e590f263c">

**Comment by pixelzoom** [comment]
The labels are in fact different on the 2 screens. On the Two Atoms screen, it's "Bond Dipole" (singular), while the Three Atoms screen is "Bond Dipoles" (plural).    Does that explain what you're seeing @Nancy-Salpepi?

**Comment by Nancy-Salpepi** [comment]
ah ok. Thanks.
