### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#28]
Finalize credits in [molecule-polarity-main.js](https://github.com/phetsims/molecule-polarity/blob/master/js/molecule-polarity-main.js).

When RC testing is completed, any credit updates should be done in both the 1.0 and master branches.

**Comment by pixelzoom** [comment]
@emily-phet please let me know if anyone else needs to be added to the credits.  (QA credits will be completed by @phet-steele after RC testing).  Here are the current credits, copied from the Java version:

![screenshot_303](https://user-images.githubusercontent.com/3046552/28043130-b686a604-658d-11e7-8b87-30e1c5e13778.png)

**Comment by pixelzoom** [comment]
Whoopsie, I pressed the close button. Reopening.

**Comment by emily-phet** [comment]
@pixelzoom Looks good to me. Let's go with this.

**Comment by kathy-phet** [comment]
And add QA team when they know who will test. :)

**Comment by pixelzoom** [comment]
Now in RC testing (https://github.com/phetsims/QA/issues/28), so assigning this issue to @phet-steele.

**Comment by phet-steele** [comment]
@pixelzoom, please add:

`Steele Dalton, Alex Dornan, Ethan Johnson`

**Comment by pixelzoom** [comment]
QA credits have been added to master and 1.0 branches.  Final credits shown below. Closing.

![screenshot_332](https://user-images.githubusercontent.com/3046552/28632579-4721a166-71ee-11e7-836d-81d9185b236b.png)
