### ISSUE TITLE
test for memory leaks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#33]
Test for memory leaks by running with `?ea&brand=phet&realMolecules&fuzzMouse` and comparing heap snapshots.

Note that this will test with the partially-implemented Real Molecules screen (sans 3D viewer).

**Comment by pixelzoom** [comment]
Consecutive heap snapshots in Chrome, at irregular intervals over 60 minutes:

29.2 MB
33.9
35.5
36.8
38.0
41.4
42.9
45.7
47.0
48.0
52.1
57.2
63.5
64.0
65.2

Pressing "Collect garbage" button had no affect on the heap size.  So looks like there's a memory leak somewhere.   That's surprising to me, since my recollection is that this sim creates everything on startup, there is nothing created dynamically.   I'll have to confirm that.  And investigate whether there is common-code stuff (PhET menu?) that is leaking.

**Comment by pixelzoom** [comment]
Running the heap test again with `?ea&brand=phet&fuzzMouse` (Real Molecules screen disabled) the results over 2 hours are:

27.4 MB
34.0
34.3
34.8
35.9
37.4
37.3

No I suspect that there's a leak somewhere in the stub implementation of the Real Molecules screen.

**Comment by pixelzoom** [comment]
The partial implementation of Real Molecules has nothing in client code that looks like it's leaking. The only possibly culprit that I can see might be recent changes to ComboBox, specifically https://github.com/phetsims/sun/commit/ba62d7378da43e24b8f8e925611a3201faa85f18 for https://github.com/phetsims/sun/issues/298.  This bit of code looks suspicious, and references https://github.com/phetsims/sun/issues/299:

```js
401      // Dispose any existing item, see https://github.com/phetsims/sun/issues/299
402      while ( selectedItemParent.children.length ) {
403        var lastNode = selectedItemParent.children[ 0 ];
404        selectedItemParent.removeChild( lastNode );
405        lastNode.dispose();
406      }
```

What looks suspicious is line 403, where `lastNode` is set to the first child.  Was something else intended?

@jonathanolson is it possible that ComboBox is leaking memory?

**Comment by pixelzoom** [comment]
Also wondering if there could be a leak here caused by PhET-iO.  I'm having a difficult time grok'ing the tandem registration, options, etc.  So difficult for me to tell if there's something amiss.  

But when the `property` value changes, a new `ComboBoxItemNode`.  It has 2 Emitters:

```js
466    this.startedCallbacksForItemFiredEmitter = new Emitter();
467    this.endedCallbacksForItemFiredEmitter = new Emitter();
```

Is it possible that something is listening to these Emitters? Or a reference is being kept somewhere to the previous ComboBoxItemNode?

**Comment by pixelzoom** [comment]
`?ea&brand=phet&realMolecules&fuzzMouse` with RealMoleculesComboBox removed from Real Molecules screen, heap snapshots over 1 hour period:

29.1 MB
34.5
34.9
35.5
36.0
36.5
37.0
37.4
37.7
37.9
38.5
39.1
40.1
40.3
40.6
40.6
40.6

So like the test without the Real Molecules screen, the test without the ComboBox eventually stabilizes at ~40MB and doesn't grow any more.  

This is further evidence that something is leaking in ComboBox.

**Comment by pixelzoom** [comment]
This test is the "Real Molecules" screen only, and only `RealMoleculesComboBox` added to `RealMoleculesScreenView`.  So there's nothing interactive except the combo box and the PhET menu. `?ea&screens=3&realMolecules&fuzzMouse&fuzzRate=1000` (Note the higher `fuzzRate`).

Heap snapshot sizes over 15 minute period:

18.5 MB
19.4 
21.4
23.9
27.5
34.3
44.0
49.2
57.4
61.6

Comparing snapshots, each comparison shows large numbers of `ComboBoxItemNode` added, and zero deleted.  The last snapshot shows 2899 instances of `ComboBoxItemNode`.

**Comment by pixelzoom** [comment]
@zepumph @samreid FYI... ComboBox appears to have a serious memory leak.

**Comment by pixelzoom** [comment]
@zepumph @samreid When the value of `property` changes, a new `ComboBoxItemNode` is created, see line 270.  I don't see anything in ComboBox.js that deregisters the previous `ComboBoxItemNode`.  Should it in fact be deregistered? Could this cause a leak in a non-PhET-iO sim?

**Comment by pixelzoom** [comment]
@jonathanolson I see that you added `ComboBoxItemNode.dispose` in https://github.com/phetsims/sun/commit/ba62d7378da43e24b8f8e925611a3201faa85f18.  Should it handle PhET-iO de-registration?

**Comment by samreid** [comment]
> @jonathanolson I see that you added `ComboBoxItemNode.dispose` in https://github.com/phetsims/sun/commit/ba62d7378da43e24b8f8e925611a3201faa85f18.  Should it handle PhET-iO de-registration?  Or is that handled by chaining to the supertype's (Rectangle) `dispose` function?

`Node.dispose` deregisters the Tandem

```js
    /**
     * Disposes the node, releasing all references that it maintained.
     * @public
     */
    dispose: function() {
      // See constructor for Node disposal checks
      if ( assert ) {
        this.isNodeDisposed = true;
      }

      Events.prototype.dispose.call( this ); // TODO: don't rely on Events

      if ( this._tandem ) {
        this._tandem.removeInstance( this );
        this._tandem = null;
      }
    }
```

**Comment by jonathanolson** [comment]
> What looks suspicious is line 403, where lastNode is set to the first child. Was something else intended?

It's as intended, but has a poor name (sorry!).

> @jonathanolson is it possible that ComboBox is leaking memory?

Possibly, I only fixed one memory leak in my changes, but didn't exhaustively scan for others.

> @jonathanolson I see that you added ComboBoxItemNode.dispose in phetsims/sun@ba62d73. Should it handle PhET-iO de-registration?

I assume Node's dispose() should handle that?

I'll look into what's going on briefly here.

**Comment by jonathanolson** [comment]
It's definitely my fault, I was using dispose() to detach children/parents, but that change wasn't actually live yet as part of https://github.com/phetsims/scenery/issues/629, so instead it's leaking. Sorry!

After that change is applied, the ComboBoxItemNode count stays fully steady at 21 during fuzzing with the above query parameters.

**Comment by jonathanolson** [comment]
Didn't check for other memory leaks, but I believe I've resolved the leak of ComboBoxItemNode.

**Comment by zepumph** [comment]
I pulled after https://github.com/phetsims/scenery/commit/66494d33f35c9d0c1a3efe70b927b650735b482a

and tried again with this link

http://localhost/molecule-polarity/molecule-polarity_en.html?ea&brand=phet&realMolecules&screens=3&fuzzMouse&fuzzRate=3000

After 45 minutes of testing, beginning at 24.2 MB, I ended at 68.8MB.

**Comment by pixelzoom** [comment]
With the test in https://github.com/phetsims/molecule-polarity/issues/33#issuecomment-313594593, I verified that the ComboBoxItemNode leak is fixed.  Memory holds steady at ~23MB, and heap comparisons show that ComboBoxItemNode is being freed (# Deleted is non-zero). 

Now I'll investigate why @zepumph is still seeing a leak in https://github.com/phetsims/molecule-polarity/issues/33#issuecomment-313754226.

**Comment by pixelzoom** [comment]
Re @zepumph's test in https://github.com/phetsims/molecule-polarity/issues/33#issuecomment-313754226...

With `?ea&brand=phet&realMolecules&screens=3&fuzzMouse&fuzzRate=3000` over 60 minutes, I see memory increasing from 21.7 to 46.5 MB, and didn't stabilize during that time.   I don't see anything obvious in heap comparisons to account for the leak.

**Comment by jonathanolson** [comment]
I'm curious, some leaks I've seen don't result in a "holding references to objects not needed", but more of an "array keeps getting appended to, so grows in size". Maybe that would describe why there wasn't any indication in heap comparisons?

**Comment by pixelzoom** [comment]
Hmmm... I let the test in https://github.com/phetsims/molecule-polarity/issues/33#issuecomment-313815896 run for another 30 minutes, and memory stabilized at ~47 MB.  That doesn't seem unreasonable, since `?screens=3` still instantiates all 3 screens.  But why did @zepumph see 68.8 MB?

**Comment by pixelzoom** [comment]
Retract that... It's not stabilized, it's still growing, 50.7 MB after another 15 minutes.

**Comment by pixelzoom** [comment]
Worked with @jonathanolson on this via Skype.  This is yet-another leak in Dialog, to be added the list in https://github.com/phetsims/joist/issues/357.  When the Options menu item is selected, a new OptionsDialog is created and passed `options.optionsNode` that was provided to Sim constructor.  In the case of molecule-polarity, `optionsNode` is a `MPOptionNode` -- see *main.js.

In the console:

```
> phet.joist.sim.options.optionsNode._parents
[ Node, Node, Node,...,Node, Node, Node ]
```

Every OptionsDialog that has ever been created is still included here.  And that's because Dialog doesn't own its `content`, but never bothered to removeChild that `content`.   

The above commit fixes this issue.  Given the state of Dialog, and how hide/dispose are so intertwined, this is a scary change, and I think it has a high probability of causing problems for someone's Dialog.  I tested AboutDialog and OptionsDialog in a couple of sims, and I'll alert PhET developers to watch for problems.

**Comment by samreid** [comment]
> ?screens=3 still instantiates all 3 screens.

Yes, all Screen objects are instantiated, but only the models and views for screen 3 are instantiated.

**Comment by pixelzoom** [comment]
Ugh.

`?ea&realMolecules&brand=phet&fuzzMouse&fuzzRate=3000` over a 3 hour period:

30.2 MB
...
107 MB

Here's a comparison of the last 2 heaps:

![screenshot_297](https://user-images.githubusercontent.com/3046552/27982478-3cee6578-635f-11e7-84b7-49fe6bfc3173.png)

Expanding the first `(array)` shows a boatload of instances of SVGDrawable subtypes. See screenshot below.  @jonathanolson is this anything that you recognize?

![screenshot_296](https://user-images.githubusercontent.com/3046552/27982483-5878e7d2-635f-11e7-943b-475510f7f78b.png)

**Comment by samreid** [comment]
On master there is still an OptionsDialog leak. (not sure if that's a known problem)

**Comment by pixelzoom** [comment]
> On master there is still an OptionsDialog leak. (not sure if that's a known problem)
 
How did you determine this?

**Comment by pixelzoom** [comment]
> On master there is still an OptionsDialog leak. (not sure if that's a known problem)
 
Not a problem that I know about.  How did you determine this?

**Comment by samreid** [comment]
Run without fuzzing: http://localhost/molecule-polarity/molecule-polarity_en.html?brand=phet&ea

Memory snapshot

do this 5 times:
 - click options dialog then dismiss the options dialog

Memory snapshot

Compare memory snapshots and sort by deltas

![image](https://user-images.githubusercontent.com/679486/27982747-877a5fee-6368-11e7-95ef-d29c0a6d0bbc.png)

Note that there are a bunch of types with 5 more instances, including the OptionsDialog (the other items may be its children?).  I suspect that many of the scenery overhead objects are related to this.

You can investigate further by commenting out `optionsNode: new MPOptionsNode(), // user interface for the Options dialog` in main and running more fuzz tests.

**Comment by jonathanolson** [comment]
I'll look into this tonight.

**Comment by jonathanolson** [comment]
Fixed another Dialog leak (not the cleanest way, but I really don't want to dive into that right now).

Checking to see if there's anything else.

**Comment by pixelzoom** [comment]
`?ea&realMolecules&brand=phet&fuzzMouse&fuzzRate=3000` over a 1-hour period:

28.8 MB
...
38.4 MB

Memory usage stabilized ~38 MB.

I'm confident that this sim will not have memory issues in practice.

To summarize:
• No memory leaks were found in sim code.
• 1 memory leak was fixed in RichText.
• 2 memory leaks were fixes in Dialog.

Closing. Thanks @jonathanolson and @samreid for your assistance.

**Comment by zepumph** [comment]
from #30

**Comment by pixelzoom** [comment]
Yes, new issue for new leak please.
