### ISSUE TITLE
replace LinkText with RichText

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#34]
See https://github.com/phetsims/joist/issues/430

**Comment by pixelzoom** [comment]
@jonathanolson can you please review my use of `links: true` for RichText in UnderDevelopmentPlane?   I'm assuming this is OK, since the text (and link) is totally contained with the source code, and there's no opportunity for links to be inserted nefariously.

**Comment by jonathanolson** [comment]
Looks good to me.

**Comment by pixelzoom** [comment]
Thanks. Closing.
