### ISSUE TITLE
Electrostatic potential color on legend scale seems reversed from Java

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/molecule-polarity#37]
So the potential color scale displayed on the molecule's atoms match the java ... but the color scale on the legend is inverted from java. 

Here is Java: 
![image](https://user-images.githubusercontent.com/5096804/28041775-e8110094-6587-11e7-8295-955a8d53184a.png)

Here is HTML
![image](https://user-images.githubusercontent.com/5096804/28041795-f7bc828e-6587-11e7-9c16-eb22e5b09cbe.png)

Java is correct.

**Comment by pixelzoom** [comment]
It's also incorrect (inverted) for Electron Density.

**Comment by pixelzoom** [comment]
Fixed the colors in the color keys. Colors applied to the molecules are unchanged.

@kathy-phet please verify in this dev version:
http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.12/molecule-polarity_en.html

**Comment by kathy-phet** [comment]
fixed

**Comment by kathy-phet** [comment]
looks good, closing.
