### ISSUE TITLE
Some garbage collection (?) make motion a bit jerky at times.

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/molecule-polarity#40]
This is not a learning goal of the sim, and in fact the rotation dynamics is not physically correct, but I do notice garbage collection making the rotation animation halt/glitch at times when I play with it. Low priority in my view, but thought I would report it.

**Comment by pixelzoom** [comment]
@kathy-phet On what platform are you experiencing "rotation animation halt/glitch"?

**Comment by kathy-phet** [comment]
Windows 7 Enterprise, Service Pack 1
Chrome: Version 59.0.3071.115 (Official Build) (64-bit)

It's like a hiccup.

**Comment by pixelzoom** [comment]
I haven't been able to reproduce this.  Maybe I'm not clear on what you're describing.

By "rotation animation", I assume you mean the animation that occurs when you have the E-field on, and you release the molecule. And that you're seeing glitchy motion when the molecule is animating into alignment with the E-field.  Is that correct?

**Comment by pixelzoom** [comment]
And is the glitch present in one screen or both?

**Comment by kathy-phet** [comment]
I played with it again. It seemed better. Still saw a few hiccups. I don't think we should worry about it. It's doesn't interfere with the learning goals. I'll show it to you on Thursday (perhaps if I rebooted it would be gone, but its not a good time to do that right now).

**Comment by pixelzoom** [comment]
Reboot shouldn't affect it.  What could affect it is the number of browser windows/tabs that you have open.   And I have no control over that :)

**Comment by pixelzoom** [comment]
@kathy-phet experienced the issue with animation when the E-field was on. She had a lot of browser tabs open.   Performance was ok after she closed tabs and restarted browser.  So we're not going to worry about this. 

Closing.
