### ISSUE TITLE
Should the hyperlink on the Real Molecules screen be translatable?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#41]
as part of #30 (code review)
I don't mean this in the sense that the translators can edit the hyperlink, because I think that will just lead to cans of worms being freed. I am just wondering if we wanted to detect the local, and adjust the link accordingly to go to the correct language of the website. So for spanish the link would be

https://phet.colorado.edu/es/simulation/legacy/molecule-polarity

**Comment by pixelzoom** [comment]
We decided not to allow translation of links because it's a security risk.  The user will be directed to the main (English) sim page, where they can then select "Translations" to choose their language.

Closing as "won't fix".
