### ISSUE TITLE
Should Real Molecules dialog always stay within screen bounds?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#42]
From code review #30 

I noticed on `stringTest=xss` and confirmed with 

http://localhost/molecule-polarity/molecule-polarity_en.html?brand=phet&ea&stringTest=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

If the string is long enough, then the dialog on the Real Molecules screen gets to be  too wide for the screen. I'm not sure if we support this, but it seems like translators could have a sentence that is this big (although unlikely). I'm not sure if we normally support a "wrap" of text that is too long. Sounds like a pain in the but. Maybe it is just up to our translators to use a sentence of the same length as ours.

**Comment by pixelzoom** [comment]
Fixed in master. Tested with `?dev&xss`, see screenshot below. @zepumph please verify.

![screenshot_52](https://user-images.githubusercontent.com/3046552/28098058-48ec3174-6671-11e7-930c-ab0ea0028bb7.png)

**Comment by zepumph** [comment]
Looks great, thanks for the speedy turnaround. Closing
