### ISSUE TITLE
PHET_IO in molecule-polarity-config.js?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#43]
As part of code review #30, @zepumph removed `PHET_IO` from molecule-polarity-config.js in https://github.com/phetsims/molecule-polarity/commit/6e226e171232cbfce832c7b9e9457fca8f67f416.   But I see that @samreid added it in https://github.com/phetsims/molecule-polarity/commit/f1205f4c7e2526699af612b8758d08e5247447e6, and apparently did so for _all_ {{REPO}}-config.js files, https://github.com/phetsims/phet-io/issues/453.  And `PHET_IO` is still in {{REPO}}-config.js for other sims that are not instrumented (e.g. function-builder-config.js).

I'm not clear on _why_ it was added by @samreid.  @zepumph please investigate whether it needs to be restored.

**Comment by pixelzoom** [comment]
Btw... If it's no longer needed here, then that's a more general issue, and it should probably be removed from _all_ {{REPO}}-config.js files where it's not needed.

**Comment by samreid** [comment]
I tried removing PHET_IO from the molarity config.js file and after doing so was unable to launch phet-io-wrappers/instance-proxies/instance-proxies.html?sim=molarity&ea

because this GET fails:
```
require-2.1.11.js:1895 GET http://localhost/molarity/js/PHET_IO/SimIFrameAPI.js?bust=1499897604691 
```

I suspect it is also necessary for PhET-iO builds.  Does this seem reasonable?

**Comment by pixelzoom** [comment]
@samreid asked:
> Does this seem reasonable?

I don't know. This sim isn't instrumented.  Should we wait to add PhET-iO dependencies as part of the instrumentation process?

**Comment by pixelzoom** [comment]
... and what was the motivation for adding PhET-iO dependencies to config.js for all sims?

**Comment by zepumph** [comment]
>I don't know. This sim isn't instrumented. Should we wait to add PhET-iO dependencies as part of the instrumentation process?

That seems reasonable to me. Isn't molarity instrumented though? I would expect it to fail in phet-io mode.

**Comment by samreid** [comment]
> Should we wait to add PhET-iO dependencies as part of the instrumentation process?

We wanted to make it so that simulations could do PhET-iO record and playback without any instrumentation.  However, it did require adding PHET_IO to the config.js files.

**Comment by pixelzoom** [comment]
Labeled for developer meeting, so we can get a consensus on when to add `PHET_IO` to config.js.

**Comment by zepumph** [comment]
>We wanted to make it so that simulations could do PhET-iO record and playback without any instrumentation. However, it did require adding PHET_IO to the config.js files.

It seems like there is always a manual step before getting a sim ready for record and playback. This is because not all ui components are instrumented for the data stream, so we have to make sure that everything is being emitted that we want. It seems reasonable that we would just add the PHET_IO dependency during that step, instead of always having it with every sim. 

I would even argue that having it on all sims could be confusing, because someone may take that as a sign that the sim is ready for record/playback when it isn't.

**Comment by pixelzoom** [comment]
My vote would be to add `ifphetio` and `PHET_IO` to config.js when it's needed.  And indicate that in https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md.

**Comment by pixelzoom** [comment]
7/13/17 dev meeting:
• restore PHET_IO in molecule-polarity-config.js
• for config.js checklist item, indicate that all config.js files will have PHET_IO and ifphetio

@zepumph will handle.

**Comment by zepumph** [comment]
in 41969824346b861c136cd8d8e1fc90dfca87be68 I reverted the dependency update.  I also updated the checklist above. Closing.
