### ISSUE TITLE
Should jsMole dir be in .gitignore?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#44]
From code review #30

>Does .gitignore match the one in simula-rasa?

I see a dir for jsmole, should that remain? I read through #15 and #22 and found that perhaps that is being phased out. @pixelzoom I'll let you decide and fix if needed.

**Comment by pixelzoom** [comment]
The entry for `jsmol-14.2.4` in .gitignore is indeed vestigial, left over from when we were pursuing JSmol as a solution for the 3D molecule viewer.  I've removed it in the above commit.
