### ISSUE TITLE
Rename Bond/MoleculeAngleHandler to *AngleDragHandler?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#45]
From code review #30.

This may be a bit clearer with what the type is doing. It also seems idiomatic with other subtypes of SimpleDragHandler.

I defer to your judgment @pixelzoom.

**Comment by pixelzoom** [comment]
That sounds reasonable, will do.

**Comment by pixelzoom** [comment]
Changes push. @zepumph please verify.

**Comment by zepumph** [comment]
Looks good, thanks.
