### ISSUE TITLE
SurfaceColorKey is a factory, not a type.

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#46]
From code review #30.

I think it is a bit confusing the way that SurfaceColorKey is used, albeit really clever.  It is named as though it is a constructed type, but the new operator is only ever used internally. I think it would be more clear to outsiders if it were renamed to surfaceColorKeyFactory, or something like that. Then SurfaceColorKey could be private to that file, and returned in the following methods as currently implemented:

```js
 return inherit( Node, SurfaceColorKey, {}, {

    /**
     * Creates the color key for black-&-white gradient.
     * @param options
     * @returns {SurfaceColorKey}
     * @public
     * @static
     */
    createElectronDensityColorKey: function( options ) {
      return new SurfaceColorKey( MPColors.BW_GRADIENT, electronDensityString, lessString, moreString, options );
    },

    /**
     * Creates the color key for red-white-blue gradient.
     * @param options
     * @returns {SurfaceColorKey}
     * @public
     * @static
     */
    createElectrostaticPotentialRWBColorKey: function( options ) {
      return new SurfaceColorKey( MPColors.RWB_GRADIENT, electrostaticPotentialString, positiveString, negativeString, options );
    },

    /**
     * Creates the color key for ROYGB gradient.
     * @param options
     * @returns {SurfaceColorKey}
     * @public
     * @static
     */
    createElectrostaticPotentialROYGBColorKey: function( options ) {
      return new SurfaceColorKey( MPColors.ROYGB_GRADIENT, electrostaticPotentialString, positiveString, negativeString, options );
    }
  } );
```

Then usage would be:
`surfaceColorKeyFactory.createElectrostaticPotentialRWBColorKey( COLOR_KEY_OPTIONS )`

instead of how it currently is

`SurfaceColorKey.createElectrostaticPotentialRWBColorKey( COLOR_KEY_OPTIONS )`

It seems weird to me that methods of SurfaceColorKey return instances of SurfaceColorKey. Please correct me if this is general practice at PhET. I haven't seen it before. As always, I defer to your judgment @pixelzoom. If we choose to leave it the way it is, then we should at least document the intended usage in the top level comment.

**Comment by pixelzoom** [comment]
SurfaceColorKey is not a factory.  It's a subtype of Node that has static factory methods contain code that would otherwise be duplicated in multiple ScreenViews.  

For example, in TwoAtomsScreenView, I could replace:

`var electronDensityColorKey = SurfaceColorKey.createElectronDensityColorKey();`

with:

` var electronDensityColorKey = new SurfaceColorKey( MPColors.BW_GRADIENT, electronDensityString, lessString, moreString );`

But then I'd need to duplicate the same thing (plus the string `require` statements) in RealMoleculesScreenView.

This is a common pattern of encapsulating duplicated code.  So I'm not going to change it.

**Comment by pixelzoom** [comment]
Reopening so @zepumph can review and has the opportunity to disagree.

**Comment by zepumph** [comment]
I understand that, and fully agree; duplicated code there is no good. I don't feel strongly about this, but the suggestion I was pondering was the following, all in `surfaceColorKeyFactory.js`:


```js
// @private
function SurfaceColorKey(){

. . . just like the current constructor
}
  moleculePolarity.register( 'SurfaceColorKey', SurfaceColorKey );
  return inherit( Node, SurfaceColorKey);


function surfaceColorKeyFactory(){
// not sure what goes in here
}
inherit( Object, surfaceColorKeyFactory, {}, {

  createElectronDensityColorKey: function( options ) {
      return new SurfaceColorKey( MPColors.BW_GRADIENT, electronDensityString, lessString, moreString, options );
    },

    createElectrostaticPotentialRWBColorKey: function( options ) {
      return new SurfaceColorKey( MPColors.RWB_GRADIENT, electrostaticPotentialString, positiveString, negativeString, options );
    },

    createElectrostaticPotentialROYGBColorKey: function( options ) {
      return new SurfaceColorKey( MPColors.ROYGB_GRADIENT, electrostaticPotentialString, positiveString, negativeString, options );
    }

});
```

Usage in a screen view:
`surfaceColorKeyFactory.createElectrostaticPotentialRWBColorKey( COLOR_KEY_OPTIONS )`


My question is if this makes more sense than what is currently implemented. 

If not, can we add a comment to `SurfaceColorKey.js` that says something like "[t]his type was developed with pre defined instances that be returned from its static methods. It was not intended to be instantiated outside of this file (with the new operator)"

**Comment by zepumph** [comment]
After seeing this same pattern in `PartialChargeNode.js`, I think the best way to proceed is to add a comment like so at the top of files like this, so people know that the developer didn't really expect the Type to be instantiated publicly.

" * Uses static factory methods to supply the needed instances for the sim."

**Comment by pixelzoom** [comment]
Documentation added, @zepumph please review.

**Comment by zepumph** [comment]
Looks great thanks.
