### ISSUE TITLE
[AtomNode] Why not extend ShadedSphereNode?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#47]
This is a question about rationale. I am often curious about the different implementations for Nodes. 
AtomNode is a Type that extends Node and has children nodes too. Is there a benefit to that versus a Type that extends that child node's Type? Could you explain if it is better to do it one way or the other? To be more clear, this is the other implementation that I am thinking of

```js
    function AtomNode( atom ) {

    ShadedSphereNode.call( this, atom.diameter, { mainColor: atom.color } );

    // name centered on atom
    var textNode = new Text( atom.name, {
      font: new PhetFont( { size: 32, weight: 'bold' } ),
      maxWidth: 0.75 * atom.diameter,
      centerX: this.centerX,
      centerY: this.centerY
    } );


    this.addChild( textNode);

    // sync location with model, unlink not needed
    atom.locationProperty.linkAttribute( this, 'translation' );
  }

**Comment by pixelzoom** [comment]
The approach I used is referred to as composition.  The approach that you're suggesting is referred to as decoration.   Both are legitimate approaches.  In this case, I prefer composition, since I don't want to expose the `ShadedSphereNode` API to the client.   Make sense?

**Comment by zepumph** [comment]
Yes thanks.
