### ISSUE TITLE
Clarify visibility annotation in DiatomicMoleculeNode

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#48]
from code review #30 
I'm confused about this comment before a batch of node declarations:

```js
// @private nodes whose visibility may change
this.partialChargeNodeA = PartialChargeNode.createOppositePartialChargeNode( molecule.atomA, molecule.bond ); // @private
    this.partialChargeNodeB = PartialChargeNode.createOppositePartialChargeNode( molecule.atomB, molecule.bond ); // @private
    this.electrostaticPotentialNode = new ElectrostaticPotentialNode( molecule ); // @private
    this.electronDensityNode = new ElectronDensityNode( molecule ); // @private
    this.bondDipoleNode = new BondDipoleNode( molecule.bond ); // @private
```

Could you be a bit more specific. I didn't realize visibility annotations could change throughout the lifetime of a sim. If I'm just ignorant please inform and sorry to both with another issue.

**Comment by pixelzoom** [comment]
You're confusing visibility of Nodes (whether they are rendered) with visibility annotations.  

I've removed the confusing comment. @zepumph please review.
