### ISSUE TITLE
TranslateArrowsNode should be in common/

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#49]
From code review #30 
I see this import line in `twoatoms/view/DiatomicMoleculeNode.js`:
`  var TranslateArrowsNode = require( 'MOLECULE_POLARITY/threeatoms/view/TranslateArrowsNode' );`

This type should be factored out to common.

**Comment by pixelzoom** [comment]
Good catch.  `TranslateArrowsNode` was originally used only in "Three Atoms", but decisions in #35 add it to "Two Atoms" too.  I've moved it to common.  Closing.
