### ISSUE TITLE
change initial orientation of the diatomic molecule?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#51]
A concern about the diatomic molecule has been voiced multiple times:  If the E-field is turned on when the molecule is in its initial orientation, the dipole is already aligned with the E-field, and there will no change in the molecule's orientation.   So the student won't get any feedback and might not use the E-field again.

Should we consider changing the default orientation?  Perhaps something like:

![screenshot_314](https://user-images.githubusercontent.com/3046552/28223706-b0998d8e-6889-11e7-8c68-6819d54b83af.png)

**Comment by kathy-phet** [comment]
I think it's important to have a horizontal orientation to have the right/left association with the sliders, but we could consider a change in the default start up of the electronegativity settings on the sliders. This setting below, would result in a flip: 
![image](https://user-images.githubusercontent.com/5096804/28224183-6856cbc0-688b-11e7-988c-64a80f61c3e3.png)
 

Or swapping the positive and negative terminals, so the e-field points the opposite direction. 

I have a slight preference for changing the orientation of the positive / negative terminals.

**Comment by kathy-phet** [comment]
@emily-phet - Thoughts on this?

**Comment by kathy-phet** [comment]
But changing the positive/negative terminals might impact more of the existing lessons. Hmmm.

**Comment by pixelzoom** [comment]
I've also wondered if we should have some visual representation of the E-field (something shown between the plates) when the E-field is on.  The presence of the positive and negative terminals is a bit subtle, and students may forget that they have the E-field "on' in the control panel.

**Comment by pixelzoom** [comment]
Having a visual representation of the E-field might also reinforce the alignment between the dipole and E-field.

**Comment by kathy-phet** [comment]
That could be nice. Subtle in the background. @emily-phet?

**Comment by pixelzoom** [comment]
Moving the discussion about E-field representation as separate issue (#52).

**Comment by pixelzoom** [comment]
My vote would be for flipping the initial direction of the dipole, as you've shown in https://github.com/phetsims/molecule-polarity/issues/51#issuecomment-315425394.

Swapping the terminals would impact not only lesson plans, but any screenshot, including the screenshot for the sim's web page.

**Comment by pixelzoom** [comment]
Also worth noting that any existing lesson plans are for the Java version.  And since the HTML5 version has visual differences, some lessons plans may need to be revised anyway.

**Comment by pixelzoom** [comment]
@emily-phet the options are:

• Flip the initial dipole direction
• Change the initial molecule orientation
• Swap the positive and negative terminals
• Do nothing

**Comment by pixelzoom** [comment]
For now I'm going to go with:
> Flip the initial dipole direction

That will assist me in testing #50, where the cueing arrows should not go away until the user moves an atom.

**Comment by emily-phet** [comment]
@pixelzoom Agreed, I think changing the initial configuration of the sliders is the least invasive way ensure turning on the e field results in molecule motion.

**Comment by pixelzoom** [comment]
Flipping the dipole was already implemented in the above commit (to facilitate testing of #50), so nothing else to do here. Closing.

**Comment by pixelzoom** [comment]
Reopening.  @kathy-phet discussed with @emily-phet, and they would like the original defaults restored, so that the default is "in phase" with the surface color key.  E.g. see screenshot below:

![screenshot_359](https://user-images.githubusercontent.com/3046552/29430311-2dcf9a64-8351-11e7-8fa6-b2d56e33cb0b.png)

Turning on the e-field in the default configuration will not result in any change to the molecule's orientation, but @kathy-phet and @emily-phet now feel that that is not a concern.

I'll publish this in maintenance release 1.0.2.

**Comment by pixelzoom** [comment]
This change is live in 1.0.2 on the PhET website:
http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.2/molecule-polarity_en.html

@kathy-phet please verify.  If it looks OK, please close this issue.

**Comment by kathy-phet** [comment]
verified! Thanks!
