### ISSUE TITLE
add a visual representation of E-field?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#52]
This came up during discussion of https://github.com/phetsims/molecule-polarity/issues/51.  I've move the related comments here.

I said:
> I've also wondered if we should have some visual representation of the E-field (something shown between the plates) when the E-field is on. The presence of the positive and negative terminals is a bit subtle, and students may forget that they have the E-field "on" in the control panel.
> 
> Having a visual representation of the E-field might also reinforce the alignment between the dipole and E-field.

@kathy-phet said:
> That could be nice. Subtle in the background. @emily-phet?

**Comment by pixelzoom** [comment]
Perhaps faint horizontal lines, with arrows pointing from positive to negative plate?

**Comment by pixelzoom** [comment]
If we have a visual representation of the E-field, we could probably leave the plates labeled with + and -.  And that facilitate assist with predicting what's going to happen when the E-field is turned on.  Currently the plates aren't labeled when the E-field is off, so if you want to predict what's going to happen, then you have to remember which plate is which.

**Comment by kathy-phet** [comment]
@pixelzoom - I think that leaving the +/- on the plates when the electric field is off could cause confusion. 

Also, note that the dipole aligns anti-parallel to the e-field. 

I'm wondering how much this is discussed in chemistry. It's definitely an interesting physics phenomena, but I'm not sure what they get into in physical chemistry around this alignment or not.

**Comment by pixelzoom** [comment]
>  I think that leaving the +/- on the plates when the electric field is off could cause confusion.

Could you elaborate?

> Also, note that the dipole aligns anti-parallel to the e-field.

Yep, understood.  But that's not at all obvious now.  Whether it's important is up to @emily-phet.

**Comment by kathy-phet** [comment]
If it has a + attached to it. I can easily think it is positively charged if I haven't noticed the e-field on/off button or I don't know that e-field is related to the charging of the plate. Chemistry students may not know that -- so by labling when you turn on the field you help them associate that idea. That this plate now is positive.

**Comment by emily-phet** [comment]
This seems like a pretty significant suggestion. I'm not sure it's worth the amount of iterations to add more e field cueing that it would take for everyone to feel comfortable with the outcome. Have we heard from teachers this is an issue? I think if it isn't broke, we shouldn't go down a rabbit hole to fix it. 

I think the simplest thing to do (design-wise) is to just not show the plates until the field is on. So e field on/off is actually adding/removing the plates. If folks don't like that, or it's technically challenging, I say we just leave the sim as-is.

**Comment by pixelzoom** [comment]
@emily-phet said:
> I think the simplest thing to do (design-wise) is to just not show the plates until the field is on.

I'll give you a dev version that removes the plates, so people can evaluate.

**Comment by pixelzoom** [comment]
Here's a dev version where the plates are shown only when the E-field is on:
http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.21/molecule-polarity_en.html

This feels pretty nice to me, and (in the absence of a visual representation of the E-field) removes any question about whether the field is on or off.

@emily-phet please review.

**Comment by emily-phet** [comment]
@pixelzoom I think this looks great! I think it will be much more clear to students and teachers. Let's keep this change.

**Comment by pixelzoom** [comment]
Excellent, closing.
