### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#54]
@emily-phet please specify how you'd like the screenshot (thumbnail and webpage) for this sim to look.  The easiest way to do that is to put the lastest dev version of the sim in the desired configuration, take as screenshot, and attach it to this issue in a comment.

For reference, the screenshot for the Java version can be seen here: https://phet.colorado.edu/en/simulation/molecule-polarity.   That screenshot is of the "Real Molecules" screen, so we'll obviously need to come up with a new screenshot configuration.

**Comment by emily-phet** [comment]
@pixelzoom Here ya go. It's just three atoms screen, no hint arrows, electric field turned on, all dipole representations turned on. If it looks odd for some reason as a thumbnail, removing the partial charge representations would be fine (they may be too small for thumbnail size).
![screen shot 2017-07-15 at 5 40 20 pm](https://user-images.githubusercontent.com/5109055/28243388-d256376e-6984-11e7-951b-9c388559f4c7.png)

**Comment by pixelzoom** [comment]
Here's approximately what the screenshot will look like in context.

Thumbnail (128x84)
![mp-small](https://user-images.githubusercontent.com/3046552/28278259-b8001258-6ad9-11e7-86c0-7c21bf9feb31.png)

Web page (300x166)
![mp-big](https://user-images.githubusercontent.com/3046552/28278332-f99ee860-6ad9-11e7-9203-9837e5c8f27a.png)

So yes, I think we should turn off partial charges.

**Comment by emily-phet** [comment]
@pixelzoom I'm not familiar with our typical practice for thumbnails. It would probably be ideal if the thumbnail did not include the control panel - so if there were a way to have the nav bar be complete (e.g., PhET logo/menu button still in the bottom right) but everything right of the rightmost plate removed from the play area, this would allow the molecules/plates/sliders to be more distinguishable at small image sizes. Do we do things like this when making thumbnails? 

Either way, I agree the partial charges should be removed.

**Comment by pixelzoom** [comment]
@emily-phet Thumbnails and sim-page images are automatically generated from the same screenshot, there is currently no way for them to be different.  Browser chrome (tabs, etc) are removed from the screenshot, but (by convention) all screenshots include the navigation bar and complete play area of the sim.

**Comment by pixelzoom** [comment]
@emily-phet Also note that the examples are provided are "approximate".  I used the image that you provided to create those examples, and it has a lot of blank space to the right of the control panel that won't be there in the actual images.  I'm guessing that you took the screenshot on a desktop with your browser a bit wider, and the final screenshot will be taken on an iPad retina.

**Comment by emily-phet** [comment]
@pixelzoom Thanks for the details. Good to know. Then yes, the same sim configuration as in the screenshots above, with no partial charges showing should be fine.

**Comment by pixelzoom** [comment]
Here's what we arrived at for the screenshot.  To reproduce:

1. Start sim, [1.0.0-rc.1](http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-rc.1/molecule-polarity_en.html) would be fine.
2. Go to "Three Atoms" screen
3. Turn on E-field
4. Turn on Bond Dipoles
5. Move atom A slightly to make cueing arrows go away

![screenshot_328](https://user-images.githubusercontent.com/3046552/28475393-311c0e58-6e09-11e7-9e70-146ddaa25a7a.png)

**Comment by pixelzoom** [comment]
@phet-steele please create this screenshot, as specified in the comment just before this one.  Please push to master and 1.0 branches, in molecule-polarity/assets/molecule-polarity-screenshot.png. You'll need to create molecule-polarity/assets/, since this sim has no other assets.

**Comment by phet-steele** [comment]
Screenshot added.
