### ISSUE TITLE
Partial charge symbol misplaced after a Reset

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-polarity#55]
The extent of this issue goes (I believe) beyond this procedure:

1. Open sim and enter the Two Atoms screen
2. Rotate the molecule
3. Press Reset All. Make sure the molecule is not at the default orientation first!
4. Enable "Partial Charges"

The position of the partial charge on "A" will be incorrectly placed until the molecule is moved or an electronegativity slider changed. This does not appear to be happening on the Three Atoms screen.

The symbol is over the A:
<img width="545" alt="screen shot 2017-07-17 at 11 46 47 am" src="https://user-images.githubusercontent.com/5863899/28281861-b960a548-6ae5-11e7-8599-a58fc32b2385.png">

Or it can just appear around the A. The position seems dependent on where the A atom was before the Reset All occurred:
<img width="432" alt="screen shot 2017-07-17 at 11 50 13 am" src="https://user-images.githubusercontent.com/5863899/28281997-1d0b14ca-6ae6-11e7-8ac9-8e5e42fc91ac.png">

Seen on macOS 10.12.5 Chrome. For phetsims/QA/issues/21.

URL: http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.23/molecule-polarity_en.html
Version: 1.0.0-dev.23 2017-07-17 16:30:59 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"fd28f6a0","branch":"master"},"babel":{"sha":"cd335880","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"80ecc40f","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"d4e70ec7","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"molecule-polarity":{"sha":"8c3e3fd8","branch":"master"},"nitroglycerin":{"sha":"6fcb2b53","branch":"master"},"phet-core":{"sha":"d8bec6c1","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"a3198c07","branch":"master"},"scenery-phet":{"sha":"effed588","branch":"master"},"sherpa":{"sha":"f1937ecb","branch":"master"},"sun":{"sha":"e1d62999","branch":"master"},"tandem":{"sha":"29cd4f63","branch":"master"}}

**Comment by pixelzoom** [comment]
Reproduced.

**Comment by pixelzoom** [comment]
@phet-steele I have not been able to reproduce this in the "Three Atoms" screen. Can you confirm that it appears to be specific to "Two Atoms"?

**Comment by phet-steele** [comment]
> This does not appear to be happening on the Three Atoms screen.

I already confirmed as such, albeit with limited testing.

**Comment by pixelzoom** [comment]
Ah, indeed you did confirm for "Three Atoms", I missed that in the description. Thanks for giving it a few more tried.

**Comment by pixelzoom** [comment]
Doesn't matter whether "Partial Charges" is checked before Reset All, charges are misplaced whether it's on or off.

**Comment by pixelzoom** [comment]
Partial charge of atom B always seems to be in the correct location.  It's just the partial charge for atom A that's off.

**Comment by pixelzoom** [comment]
The problem was that the charge location was not being updated when the charge was invisible. Reset All apparent made the charge invisible, then moved the atom.  So the charge was then in the wrong (old) location.  Fixed in the above commit by repositioning the charge when it becomes visible.

@phet-steele please review in master.

**Comment by phet-steele** [comment]
👍
