### ISSUE TITLE
Molecule flips when switching written dipole direction?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-polarity#56]
Simply changing the written direction of bond dipoles shouldn't flip the orientation of a molecule in an electric field, right?

![molpol01](https://user-images.githubusercontent.com/5863899/28284232-7e502dea-6aed-11e7-9c11-2fd895efdebe.gif)

Seen on macOS 10.12.5 Chrome. For phetsims/QA#21.

URL: http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.23/molecule-polarity_en.html
Version: 1.0.0-dev.23 2017-07-17 16:30:59 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"fd28f6a0","branch":"master"},"babel":{"sha":"cd335880","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"80ecc40f","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"d4e70ec7","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"molecule-polarity":{"sha":"8c3e3fd8","branch":"master"},"nitroglycerin":{"sha":"6fcb2b53","branch":"master"},"phet-core":{"sha":"d8bec6c1","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"a3198c07","branch":"master"},"scenery-phet":{"sha":"effed588","branch":"master"},"sherpa":{"sha":"f1937ecb","branch":"master"},"sun":{"sha":"e1d62999","branch":"master"},"tandem":{"sha":"29cd4f63","branch":"master"}}

**Comment by pixelzoom** [comment]
The sim supports 2 convention for direction of dipoles: positive-to-negative (the default) or negative-to-positive (IUPAC convention).  For positive-to-negative, the dipole is anti-parallel to the E-field.  But I suspect that it should be _parallel_ to the E-field for negative-to-positive, and that's not being handled.  So the direction that the dipoles are pointing should change, but the molecule's orientation should _not_ change.

@emily-phet can you please confirm?

**Comment by pixelzoom** [comment]
This option (switching dipole convention) was not present in the Java version, so I have nothing to compare to.  The request for adding it in the HTML5 version was made by @emily-phet in https://github.com/phetsims/molecule-polarity/issues/5.

I'm guessing that rather than "flip the sign when computing the magnitude of the bond dipoles" (https://github.com/phetsims/molecule-polarity/issues/5#issuecomment-54002616) I need to leave the magnitude unchanged and change the direction that the dipole points.

**Comment by pixelzoom** [comment]
After going down the wrong path, I backtracked and discovered a simple solution.  Yes, I still need to flip the polarity of bond dipoles.  But I had neglected to compensate for that when computing the E-field alignment.  So now that it handled properly. 

@phet-steele @emily-phet please verify in this dev version:

 http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.24/molecule-polarity_en.html

**Comment by phet-steele** [comment]
The above dev link behaves as I would expect.

**Comment by pixelzoom** [comment]
@emily-phet this is in your court. If it looks OK, please close.

**Comment by emily-phet** [comment]
@pixelzoom Yes, it's just the arrow representation that needs to change...nothing to do with the actual physics of the simulation. This looks good to me.
