### ISSUE TITLE
surface color doesn't match the color key when delta EN == 0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#58]
Related to phetsims/QA#21, discussed via Skype.

@phet-steele noticed that when deltaEN == 0, the surface color doesn't match the midpoint of the Electron Density color key.   

I determined that this is because the color key and molecule surface are using colors that have alpha=0.72.  But when deltaEN == 0, we're using an opaque color:

`NEUTRAL_GRAY: 'rgb( 128, 128, 128 )'`

Adding alpha to `NEUTRAL_GRAY` should fix the issue.  

But I'm also wondering why we added alpha to the Electron Density and Electrostatic Potential surfaces, because there's no alpha in the Java version.

**Comment by pixelzoom** [comment]
And if we do want transparency in these surfaces, it would be better to set the opacity of their associated Nodes, rather than including alpha in every color.

**Comment by pixelzoom** [comment]
@phet-steele pointed out that alpha was added so that partial charges will be visible on black surface, see https://github.com/phetsims/molecule-polarity/issues/1.

**Comment by pixelzoom** [comment]
According to @jonathanolson, gradient with colors that have alpha will have better performance. There's also the issue that we want a solid black stroke around the color keys.   So I'll leave this as is.

**Comment by phet-steele** [comment]
> So I'll leave this as is.

As is with NEUTRAL_GRAY using SURFACE_ALPHA, right?

**Comment by pixelzoom** [comment]
Yes.

**Comment by pixelzoom** [comment]
@phet-steele please verify in master.

**Comment by phet-steele** [comment]
Aw yea the colors look so much better!
