### ISSUE TITLE
Cueing arrows need to reappear after Reset All

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-polarity#59]
This sim is inconsistent with the rest of PhET by not bringing the cueing arrows back after a Reset All.

For phetsims/QA/issues/21.

**Comment by pixelzoom** [comment]
Examples?

**Comment by phet-steele** [comment]
atomic-interactions
bending-light (sort of)
faradays-law
friction
make-a-ten
states-of-matter (sort of)
unit-rates
wave-on-a-string
area-model-multiplication
capacitor-lab-basics

**Comment by pixelzoom** [comment]
I can certainly make the cueing arrows come back on Reset All.  But:

(1) It seems unnecessary and potentially annoying.  The purpose of the arrows was to cue the student _once_ about what interacting with the atoms will do.  After they've interacted, then they don't need to see the arrows anymore.  Currently, Reset All doesn't affect the cueing arrows at all - if they haven't interacted with the arrows, they remain; if they've already moved the atom, then the arrows don't reappear. 

(2) It's going to be über complicated to restore the arrows. Implementing the current behavior requires different listeners for the initial behavior vs the mouse-over behavior.   I'd need to remove the mouse-over listeners and restore the initial listeners.  Happy to do that if there's some real benefit, but see (1).

(3) Being consistent doesn't equal being useful.  I could make the same "unnecessary" argument about "initial cues" in other sims.

@emily-phet your call.

**Comment by pixelzoom** [comment]
@kathy-phet you're also invited to weigh in, since you specified the current behavior.

**Comment by pixelzoom** [comment]
For the record, the specification for the cueing arrows said nothing about restoring them on Reset All. It specified that they should be made visible "on startup", then disappear once the user has completed an associated interaction.  See https://github.com/phetsims/molecule-polarity/issues/50#issuecomment-315420828.

**Comment by phet-steele** [comment]
FTR, this would be the ONLY sim that doesn't bring the cueing arrows back if we went that route.

**Comment by pixelzoom** [comment]
@phet-steele Other than consistency with other sims, what is the advantage of bringing the cueing arrows back after the user has successfully performed the interaction that the arrows are intended to indicate?

**Comment by emily-phet** [comment]
@pixelzoom Typically I'd be on board for "consistency", but in this case, the rotate arrow on the second screen is the consistency deal breaker for me. I would be annoyed if every time I reset I had to move the atoms *and* rotate the molecule to get the hints to go away. 

I don't recall (though I could be wrong) having *two different* types of hint arrows showing at the same time...requiring two different actions be taken by the user to remove them each time they reset. 

Let's proceed with the sim as is - no hints appear after reset, they only show on sim start until the user makes the required action. Then, never seen again.

**Comment by pixelzoom** [comment]
@emily-phet got it, will leave as is.

@phet-steele thanks for noticing and reporting the fact that this was inconsistent.

Closing.

**Comment by phet-steele** [comment]
@emily-phet @pixelzoom I believe this goes beyond a simple discussion about consistency. When we talk about a "Reset All" button, there is a particular weight that the button carries on its shoulders, if you will.

Generally, the convention has been that a Reset All button returns the sim to its “startup state.” The button quite literally resets EVERYTHING. If the goal is to “start over” without resetting everything, the convention has been to use a “Return” button (FAMB, ESPB,  WOAS, Masses & Springs, Pendulum Lab) or “Reset” button (BASE, GAO, Unit Rates).

> Other than consistency with other sims, what is the advantage of bringing the cueing arrows back after the user has successfully performed the interaction that the arrows are intended to indicate?

A teacher may ask students to reset the sim (or a student may pass control to another) at the end of a lesson to get ready for the next group of students coming in. In this situation, the cueing arrows would not be visible to the 2nd group of students. Generally, we simply cannot assume that the person pressing the Reset All button will be the same person to subsequently use it.

@emily-phet said in https://github.com/phetsims/molecule-polarity/issues/59#issuecomment-315913662:
> Typically I'd be on board for "consistency", but in this case, the rotate arrow on the second screen is the consistency deal breaker for me. I would be annoyed if every time I reset I had to move the atoms and rotate the molecule to get the hints to go away.

This point is now entirely moot after https://github.com/phetsims/molecule-polarity/issues/50#issuecomment-316260644. Both arrows now disappear on a single user interaction. Since it looks like annoyance of having to perform multiple interactions is now gone, I vote we proceed with with having the hint reappear after Reset All.

**Comment by pixelzoom** [comment]
@emily-phet your call.

**Comment by ariel-phet** [comment]
@emily-phet agreed with @phet-steele - Reset All should always be assumed to completely reset the sim.

**Comment by pixelzoom** [comment]
Sounds like @ariel-phet has made the call.  I will proceed with reseting the arrows.

**Comment by emily-phet** [comment]
Sounds good. Note: I concluded this yesterday [here](https://github.com/phetsims/molecule-polarity/issues/50#issuecomment-316260644). Ultimately, the issue was a poor design choice that needed to be revised - we were requiring too much of the user to make all the hints go away in the prior iteration - so requiring that the user do these actions after each reset was too much (hence the desire to stray from typical reset behavior). By simplifying how the hints are removed, there's no issue with the typical reset behavior.

**Comment by pixelzoom** [comment]
Implemented in [1.0.0-dev.26](http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.26/molecule-polarity_en.html).  @phet-steele @emily-phet please review.

The implementation of the cueing arrows now accounts for 1/3 of the implementation of the molecule views.  I hope these arrow turn out to be effective.

**Comment by emily-phet** [comment]
@pixelzoom Looks great to me.

**Comment by phet-steele** [comment]
@pixelzoom they are behaving nicely on macOS Chrome and iPad Air 2 10.3.2. Thank you! Back to you if there is anything left to do.

**Comment by pixelzoom** [comment]
Stick a fork in me, I'm done.
