### ISSUE TITLE
Should a 'ControlPanel.js' Type be factored out?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#60]
from code review #30 
I see a lot of duplicated code in all three of the control panels. Perhaps there is a way to save code by factoring that out into its own file. jsinspect noticed multiple sections in all three control panels that were basically the exact same.

**Comment by pixelzoom** [comment]
Factoring out ControlPanel.js feels a bit "forced" to me.  There are significant differences between all 3 control panels, especially the set of "View" check boxes.  What they share is parts of the control panel, specifically the "Surface" and "Electric Field" controls.  I'll look at factoring out SurfaceControl.js and ElectricFieldControl.js, then use those in the existing control panels.

**Comment by zepumph** [comment]
I definitely understand about the "forced" feeling. Your plan sounds like a good one. If we find that it isn't helpful than I think it is fine how it is.

**Comment by pixelzoom** [comment]
Major changes to control panels, see above commits.

Summary of new types:

MPControlPanel - base type, responsible for inserting horizontal separators
SurfaceControl - title and radio buttons for selecting the surface
EFieldControl - title and on/off button for e-field
TwoAtomsViewControls - 'View' title and check boxes for Two Atoms
ThreeAtomsViewControls - 'View' title and check boxes for Three Atoms
RealMoleculesViewControls - 'View' title and check boxes for Real Molecules

Example usage in TwoAtomsScreenView:

```js
    var controlPanel = new MPControlPanel( [
      new TwoAtomsViewControls( viewProperties ),
      new SurfaceControl( viewProperties.surfaceTypeProperty ),
      new EFieldControl( model.eField.enabledProperty )
    ] );
```

@zepumph please review.

**Comment by pixelzoom** [comment]
Btw... I compared to [1.0.0-dev.24](http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.24/molecule-polarity_en.html?realMolecules) (looks identical) and tested with 
`?ea&realMolecules&stringTest=long`.

**Comment by zepumph** [comment]
This looks really nice. Thanks, closing
