### ISSUE TITLE
ElectronDensityNode and ElectrostaticPotentialNode are basically the same file

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#61]
from code review #30 

When comparing the two files in intellij, it looks more like a commit diff than different files, there are about 10 or so changes. It seems like this could probably be combined into a "2DSurfaceNode" or something that both of these nodes can use with options. @pixelzoom please comment if you think this refactoring is not worth the effort. 

To me it was a bit confusing to see two fully separate files for the same looking node (just different colors). It also isn't parallel to the general use "SurfaceColorKey.js" which creates a key for any of the surfaces.

**Comment by pixelzoom** [comment]
Yeah, looks like there should be a SurfaceNode based type.

**Comment by pixelzoom** [comment]
I factored out `SurfaceNode`, an abstract base type, in the above commit.  The subtypes (`ElectronDensityNode` and `ElectrostaticPotentialNode`) implement the `updateFill` method, which is the bit that differs for these 2 surface types. 

@zepumph please review.

**Comment by zepumph** [comment]
Looks great. Closing
