### ISSUE TITLE
Convert Properties that are booleans to BooleanProperties?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#63]
from code review #30 
I'm sure I see the added value of this, but maybe you do. I know it helps when it comes to PhET-iO instrumentation, but only a bit, and that is far down the road. Your call.

**Comment by pixelzoom** [comment]
FYI... When this sim was written (2014) there was no BooleanProperty, or any other type-specific Properties.

**Comment by pixelzoom** [comment]
Done, @zepumph please review.

**Comment by pixelzoom** [comment]
Btw... BooleanProperty is used for all of the check boxes, and the E-field on/off switch.

**Comment by zepumph** [comment]
>FYI... When this sim was written (2014) there was no BooleanProperty, or any other type-specific Properties. 

Ahhh makes sense, thanks for informing. All looks good here. Closing

**Comment by zepumph** [comment]
>BooleanProperty is used for all of the check boxes, and the E-field on/off switch.

Is this directed at me as a "when you are developing this is what phet does" or more of a "this is how it is implemented in this sim"?

**Comment by pixelzoom** [comment]
Just an FYI about where the BooleanProperties are used, in case you wanted to check to see if I missed any.
