### ISSUE TITLE
Move PointySliderThumb to common code?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#64]
From code review #30 

I see this todo: `//TODO generalize and move to common code, depending on resolution to #39`

Promoting to issue here. #39 is closed, and the TODO does not make it clear what the next step is. @pixelzoom what should be done?

**Comment by pixelzoom** [comment]
Tracking the issue of whether PointyThumb is generally useful in https://github.com/phetsims/sun/issues/306.

**Comment by zepumph** [comment]
Thanks!
