### ISSUE TITLE
clean up UnderDevelopmentPlane ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#69]
In https://github.com/phetsims/molecule-polarity/issues/30#issuecomment-316509825, @zepumph said:
> The `UnderDevelopmentPlane.js` is a bit messy. I don't think it is a big deal because it is "temporary" (what ever that means by phet sim development standards). It could use some variable names and less nesting. @pixelzoom it's your call if you think that is worth your time for such a temporary and simple Node.

What do you find messy about it?  There's more "nesting" of instantiation than I typically use, but certainly not any more than some developers.   The only duplication that I see is `PhetFont(16)`, and that's just coincidental - the text and link could (and did) have different font sizes.

**Comment by zepumph** [comment]
My thoughts were about 

```js
    var vBox = new VBox( {
      align: 'left',
      spacing: 20,
      children: [
        new Text( underDevelopmentLine1String, {
          font: new PhetFont( 22 ),
          maxWidth: maxTextWidth
        } ),
        new VBox( {
          align: 'left',
          children: [
            new Text( underDevelopmentLine2String, {
              font: new PhetFont( 16 ),
              maxWidth: maxTextWidth
            } ),
            new RichText( linkText, {
              links: true, // allow links in linkText
              font: new PhetFont( 16 ),
              maxWidth: maxTextWidth
            } )
          ]
        } )
      ]
    } );
```

I too don't think it is so bad, I mentioned it because it was atypical more than it being really problematic.

**Comment by pixelzoom** [comment]
What don't you like about it? The nested structure?

**Comment by ariel-phet** [comment]
Specificity @zepumph ....Specificity :)

**Comment by zepumph** [comment]
Sorry folks. Yes indeed the nested structure was what I was looking at. After discussing it through, I think it is best as is. I mentioned it because I was not used to so much node creation without variable names. To me it looked sloppy. I feel good to close now without action.

**Comment by pixelzoom** [comment]
I agree, nesting like this is not desirable - difficult to read and maintain.  But plan to see it in other PhET code, because it's a style preferred by some of the other PhET developers.
