### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#71]
from code review #30 

I fuzzMoused  three separate times for over an hour each time the memory increased over 10MB. I don't know if that is large enough to warrant the title of "leak" but it wasn't tapering off, so I thought it warranted an issue to discuss.

The following showing a fuzzRate of 3000 for an hour (it starts at 50MB because I had a caching problem resolved in  #70 ):

![image](https://user-images.githubusercontent.com/6856943/28392173-497cc06e-6c8d-11e7-8ba7-0dc507bbac2a.png)

**Comment by pixelzoom** [comment]
Heap comparison?

**Comment by zepumph** [comment]
Still quite unsure about how to read them. I didn't find anything obvious that was mentioned during @jessegreenberg and my recent briefing by @jonathanolson. Would you mind calling to share screens for it. I think there is still a lot to learn about what to look for.

**Comment by pixelzoom** [comment]
> Would you mind calling to share screens for it. I think there is still a lot to learn about what to look for.

Unlikely before Monday.

**Comment by zepumph** [comment]
Ok I'll see what I can do.

**Comment by zepumph** [comment]
With a fuzzRate of 5000, I let it go for 2 hours, and here are the heap sizes. 
![image](https://user-images.githubusercontent.com/6856943/28394764-d4ff9702-6c9b-11e7-9d59-f1147a8427fc.png)

It seems like it really tapered off at about 11MB. It took a long time to taper off, I'm not sure what that means. In the heap comparisons nothing really stood out to me. most deltas were in the Array and Object top level rows. Here is an example of a comparison. 

![image](https://user-images.githubusercontent.com/6856943/28394863-88bae06c-6c9c-11e7-9f26-e1df662e8805.png)

**Comment by zepumph** [comment]
After continuing that same tab this morning for multiple hours, I see that it did level off. Closing this issue, there isn't a memory leak.

![image](https://user-images.githubusercontent.com/6856943/28438695-82b722ac-6d4b-11e7-93f7-03c16340cd3f.png)
