### ISSUE TITLE
Dispose or document Bond.dipoleProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#72]
from code review #30  
This DerivedProperty is never disposed, but it is also not documented that/why dispose is not needed like all other places in the repo.

**Comment by pixelzoom** [comment]
From implementation-notes.md:

> All objects created in this simulation exist for the lifetime of the simulation, so there is no need to call `dispose`.

But I added a comment:

```js
    // @public dispose not needed, exists for the lifetime of the sim
    this.dipoleProperty = new DerivedProperty( [
```

**Comment by zepumph** [comment]
Ok right, just making sure. Thanks for the comment.
