### ISSUE TITLE
interviews for cueing arrows

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#73]
We made significant changes to the visual cues for moving atoms. See #50 and #59.  These should be vetted in interviews.

In https://github.com/phetsims/molecule-polarity/issues/50#issuecomment-316243514, I said:
> I don't know if there's any real deadline for this sim. But I do think that it's important that this particular feature be vetted via interviews before the sim start RC testing.

In https://github.com/phetsims/molecule-polarity/issues/50#issuecomment-316536715 @arouinfar replied:
> Agreed that the cueing arrows should be vetted. Thanks for letting me know the timeline @pixelzoom. My best guess is that I'll be scheduling the next round of interviews for late next week.
> 
> I really like the behavior in dev.26, by the way. My gut feeling is that they will work as intended, but I'll report back once the interviews take place.

Assigning to @emily-phet and @arouinfar to coordinate.  Unless I hear otherwise, RC testing will be blocked until this issue is closed.

**Comment by emily-phet** [comment]
@pixelzoom I don't think formal interviews are needed. 

@arouinfar if you could take a tablet with the sim downstairs in the physics building and ask a couple of students to play with it for a minute, that should suffice. If they move the atoms directly in any way, thank them and move on. If after 60-90seconds they don't directly move an atom...take note and move on.

**Comment by arouinfar** [comment]
Following @emily-phet's suggestion, I took an iPad down to the physics labs, and was able to get one student to stop for a few minutes. On the Two Molecules Screen, his first action was to adjust the electronegativity sliders, and then he rotated the atoms. On the Three Molecules screen, he almost immediately rotated the center molecule and dragged the outer molecules. It appears that the cueing arrows are serving their intended purpose.

If @pixelzoom or @emily-phet thinks it's worthwhile, I'll try again tomorrow (lectures are done for the day, and the next labs get out while I'm in design meeting).

**Comment by pixelzoom** [comment]
@emily-phet @arouinfar up to you on when you feel that you have enough evidence that this is effective.

Dev testing is completed (https://github.com/phetsims/QA/issues/21) so we're ready to starting RC testing whenever this issue is closed.

**Comment by arouinfar** [comment]
@pixelzoom @emily-phet I've decided to do one more informal interview. Physics lectures let out in half an hour, so I'll report back soon.

**Comment by arouinfar** [comment]
Did two more informal interviews. First student focused more on the sliders and radio buttons, but rotated the atoms when asked, "can you find a way to move the atoms?". Second student immediately rotated the atoms.  

Overall, 2/3 students moved/rotated the atoms very early in their interaction with the sim, so I'd say the cueing arrows are doing their job. You're clear to proceed with RC testing @pixelzoom.

**Comment by arouinfar** [comment]
I'll add that the student who needed to be prompted to rotate the atoms seemed like she was in a bit of a rush, and may have eventually moved/rotated the atoms if in a more formal interview setting. I'd call that interview inconclusive rather than a failure.

**Comment by pixelzoom** [comment]
Thanks @arouinfar, I'm proceeding with RC testing.
