### ISSUE TITLE
Items to Include in Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-polarity#74]
I'm volunteering myself to write the Teacher Tips, but could use some input from @emily-phet if there are any model simplifications (that aren't already documented in the Java tips) that should be included.

From the Legacy Tips
- [x] In interviews, no students thought you can change the electronegativity of a **real** atom.
- [x] The outer atoms (A&C) do not repel one another (see Molecule Shapes)
- [x] The views and surfaces are based on the electronegativity difference set by the slider. In the 3-atom tab, the AB and BC bonds are treated independently.
- [x] Molecular dipole is the sum of the bond dipoles

Additionally, we'll need to document
- [x] Real Molecules available in Java only

**Comment by emily-phet** [comment]
@arouinfar I'm not aware of any other model changes. 
@pixelzoom Please weigh in here if there were any model changes worth mentioning to teachers.

**Comment by arouinfar** [comment]
Thanks @emily-phet!

**Comment by arouinfar** [comment]
The Teacher Tips have been completed, so unassigning myself for now. @pixelzoom if you can think of any additional model simplifications that should be documented in the Tips, please let me know. Otherwise, feel free to close this issue.

**Comment by pixelzoom** [comment]
@arouinfar Where are the completed Teacher Tips, so I have context for my feedback?

**Comment by arouinfar** [comment]
@pixelzoom I was asking you to review the model simplifications/things to note listed in https://github.com/phetsims/molecule-polarity/issues/74#issue-244473068, but you're more than welcome to review the Tips document instead: [molecule-polarity-html5-guide.pdf](https://github.com/phetsims/molecule-polarity/files/1177189/molecule-polarity-html5-guide.pdf)

**Comment by pixelzoom** [comment]
Typo in "Model Simplications" section of molecule-polarity-html5-guide.pdf.

> The Real Molecules screen is not currently available in HTML5. If your device runs Java, you can
use Java version of the sim.

.. should be "the Java version".

**Comment by pixelzoom** [comment]
A simplification noted in [model.md](https://github.com/phetsims/molecule-polarity/blob/master/doc/model.md) that's not in molecule-polarity-html5-guide.pdf:

> **Bond dipoles** are parallel to the bond axis, and their length is linearly proportional
to delta EN. Note that this is a simplification; in reality, dipole is not influenced
solely by EN.

You might want to read through model.md to see if there's anything else that you want to mention.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I'll correct the typo, add the simplification noted in https://github.com/phetsims/molecule-polarity/issues/74#issuecomment-318124472, and review model.md to see if there's anything else I've missed.

**Comment by arouinfar** [comment]
I expanded the Model Simplifications section quite a bit based on [model.md](https://github.com/phetsims/molecule-polarity/blob/master/doc/model.md) and have uploaded the tips. Thanks again @pixelzoom!
