### ISSUE TITLE
Create Sim Primer

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/molecule-polarity#75]
A sim primer should be made at some point for this sim, but quite low priority.

**Comment by arouinfar** [comment]
- [ ] Draft script
- [ ] Record rough version for script verification 
- [ ] Review script verification draft, and adjust script as necessary 
- [ ] Record another draft
- [ ] Review 2nd draft
- [ ] Produce primer and upload 
- [ ] Caption primer

**Comment by arouinfar** [comment]
Primer has been uploaded to the PhET website. Closing.
