### ISSUE TITLE
Minor Fleshing out of design document

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/molecule-polarity#76]
@arouinfar I made a "stub" for a design document for this sim. Could you put in a few comments/screenshots about the cueing arrows while fresh in our minds? I don't think it needs to be much, and we can more fully flesh out this doc one day when we put in a 3rd screen.

Maybe also a quick mention of the following:
- sliders moved to the bottom of the screen to be touch friendly
- E-field plates only appear when electric field on (different than Java version)

**Comment by arouinfar** [comment]
@ariel-phet done. Inspiration struck, so I quickly filled in most sections of the doc. There's probably more than can be fleshed out at a later date, but it should be good enough for now.
