### ISSUE TITLE
Radio buttons a bit large

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/molecule-polarity#77]
I missed this when we were publishing, no need to fix any time soon. Noting for next time we work on this sim.

The radio buttons are currently a bit larger than standard (we have moved to a standard where the radio button diameter is basically the same size as the first letter of the label)

![molpol](https://user-images.githubusercontent.com/4051174/28933456-5c3682a4-783a-11e7-8120-5c306e1a3188.PNG)

**Comment by pixelzoom** [comment]
Can't say that I agree with this standard.  And it certainly won'y hold up when long text gets scaled for i18n.  But I'll handle it.

**Comment by pixelzoom** [comment]
Question: Does this "standard" also apply to check boxes?  See control panel from Molecule Polarity below. 

![screenshot_334](https://user-images.githubusercontent.com/3046552/29139792-5dd7def8-7d05-11e7-97f1-ea7cd0c6155e.png)

**Comment by pixelzoom** [comment]
Here's what it looks like if I apply the "standard" (AquaRadioButton `radius:8`):

![screenshot_335](https://user-images.githubusercontent.com/3046552/29139928-e1ca6ca8-7d05-11e7-8969-568d24a6f809.png)

This looks unbalanced to me.  The radio buttons are noticeably smaller than the check boxes.  

This looks better, but doesn't technically meet the standard (AquaRadioButton `radius:10`):

![screenshot_336](https://user-images.githubusercontent.com/3046552/29139971-111ca08e-7d06-11e7-9dd8-68f198dee609.png)

@ariel-phet how to proceed?

**Comment by pixelzoom** [comment]
My recommendation is to leave the check boxes alone, and go with `radius:10` for the radio buttons. Making all of these controls smaller would have no benefits, only a negative effect on usability.

**Comment by ariel-phet** [comment]
@pixelzoom perhaps I should say when I said standard I meant "this is what we have generally been doing - approximately" - it is not particularly rigid. Design guideline would probably be a better phrasing.

leave the check boxes alone, and go with `radius:10` for the radio buttons seems fine to me.

It would be fine to change this in master and just wait until the next release (even if that is a long time from now)

**Comment by pixelzoom** [comment]
Note to self: radio buttons are in SurfaceTypeControl

**Comment by pixelzoom** [comment]
Changed to `radius:10` in master and 1.0 branches.  This change will be published the next time there is a production deploy.

**Comment by pixelzoom** [comment]
No need for a test cycle, since this involved changing `radius:12` to `radius:10` in 1 place, and was tested in master and 1.0.  Closing.

**Comment by pixelzoom** [comment]
Reopening. I'm going to publish a maintenance release so that HEAD of 1.0 branch doesn't contain unpublished changes.  My understanding is that would complicate batch maintenance releases.

**Comment by pixelzoom** [comment]
Published in 1.0.1, see https://phet.colorado.edu/en/simulation/molecule-polarity.

Closing.
