### ISSUE TITLE
Google form user suggestion: Direction dipole points

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/molecule-polarity#78]
> This demo is misses an important point. Consider carbon monoxide.  Oxygen is more electronegative than carbon.  Which way does the dipole point? This seems clear based on your demo.  But what if you ask about the formal charges.  Oxygen is plus 1 and carbon is minus one.  Based on these data one would predict the dipole points the opposite way.  One must consider both formal charge AND electronegativity.  In reality, in CO carbon has a small negative charge and oxygen a small positive charge.  So my point is that if you only consider electronegativity you have oversimplified the physics to the point where you can get misleading results.

**Comment by pixelzoom** [comment]
@oliver-phet Does this need to be assigned to someone to reply?

**Comment by oliver-phet** [comment]
Assigning to @ariel-phet to decide if this is worth pursuing, delegate, and prioritize.

**Comment by pixelzoom** [comment]
I asked about this issue because it is a criticism, not a feature request.  And PhET typically has a subject matter expert (often the lead designer) respond to this type of feedback in a timely manner.

**Comment by ariel-phet** [comment]
@oliver-phet @pixelzoom I don't think anything about the sim needs to be changed, but the user should be replied to... I will see if I can get a response (maybe Robert will have something to say).

**Comment by ariel-phet** [comment]
Email sent to Robert Parson and Emily Borda with @oliver-phet cc'ed. Hopefully they will have a response to the user issue.

**Comment by ariel-phet** [comment]
Robert wrote:

> 
> Ack - ever since that sim was published I’ve been waiting  for somebody to bring this up. CO is one of those once-in-a-million “exceptions to the rule” that show up now and then. I don’t think there is any simple way of explaining why the dipole in CO points the “wrong" way short of a full-scale quantum mechanics calculation, in particular I don’t
> think the "formal charge" has anything to do with it - the explanations in freshman textbooks are post-hoc rationalizations. Give me a couple of days to check references so that I can give a better answer and avoid saying anything that’s outright wrong.

**Comment by ariel-phet** [comment]
Robert's expanded explanation:

> 
> Thank you for your comment.  You are correct to point out that carbon monoxide violates the usual rule that in covalent bonds, the more electronegative atom has a partial negative charge. This is not the only thing that is peculiar about carbon monoxide from the point of view of introductory chemistry: among other things it is a stable compound in which carbon forms three covalent bonds, rather than four, and oxygen forms three covalent bonds, rather than two. This in itself demonstrates that the bonding in CO is more complicated than the simple models would suggest, and that the properties of molecules cannot always be reduced to the properties of individual atoms.  We don’t believe that introducing the concept of formal charge really helps here. Formal charge is an accounting device that is used to estimate the the relative contributions of “resonance structures” to the true molecular structure. It is not, and was never intended to be, a description of the actual charge distribution in a molecule. An accurate description of the charge distribution in an “anomalous” molecule such as CO requires a sophisticated quantum-mechanical analysis. Indeed, CO has often been used as a test case for the accuracy of quantum chemistry methods - see, for example, Scuseria et al, “ The dipole moment of carbon monoxide”, J. Chem. Phys. 94, 6660 (1991); doi: 10.1063/1.460293. 
> 
> We tried to address the point that electronegativity is not the only thing that determines molecular polarity in the third tab of the sim, “Real Molecules”, which right now is only included in the original Java sim – it has not yet been converted to HTML 5. In this tab, one of our examples is ozone,  which we show to have a dipole moment in spite of the fact that all three atoms have the same electronegativity. We did not include CO in this list because we thought it would be too confusing – CO is a very rare exception to a rule that holds for the vast majority of diatomic molecules.

**Comment by oliver-phet** [comment]
Email to user sent with Robert's explanation. Closing for now.

**Comment by oliver-phet** [comment]
Reply from user:

> Thanks for the answer.   I know Robert well.  His answer is excellent as is your response.
I love phet demos.  Keep up the good work.
