### ISSUE TITLE
state not saved correctly

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#79]
Copied from https://github.com/phetsims/phet-io/issues/851 to this repo

@samreid said
From #319:

1. Some photons are "leaking" and not getting removed from state
2. Clicking "Launch" yields a "duplicate item" issue
3. Molecule state is not saved.

And we reproduced this problem and January 11th, 2017

**Comment by pixelzoom** [comment]
@zepumph I don't see any commits that indicate this was fixed in phetsims/phet-io#851. Is this still a problem? Did you close this issue by mistake?

**Comment by pixelzoom** [comment]
Ah... Looks like you created this issue in the wrong repo, should have been in molecules-and-light.  Closing.

**Comment by zepumph** [comment]
Sorry about that. no communication on that one, see https://github.com/phetsims/molecules-and-light/issues/154 for the proper living space for this issue.
