### ISSUE TITLE
Publish PhET-iO 1.1 RC to support research study (4/4/2021)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#87]
This issue was the motivation for #85 (Add basic PhET-iO instrumentation).

A research collaborator would like to use this sim for a study.  @kathy-phet provided some info on Slack, here's my summary: 

* The study is scheduled for "end of March", and the researcher would like the sim by "mid March"
* PhET-iO instrumentation is required, and "saving state is of primary importance" (#85)
* PhET will provide a link to ~~a dev version~~ an RC version.
* QA will do ~~some testing~~ "RC-Research" testing, as will @kathy-phet, @arouinfar, and the researcher.
* Testing of "Metacog collection" will be included
* The researcher has started "looking at the back end data stream already"

Unless I hear otherwise, I'll assume "end of March" means 3/31/21.

**Comment by pixelzoom** [comment]
I would like to discuss the plan to provide a dev version.  Two concerns:

(1) The dev team has repeatedly recommended against providing dev versions. A dev version cannot be patched via PhET processes and tools.  An RC version has no additional cost, and provides all of the maintenance benefits.

(2) The dev team has expressed concerns about the impact of study traffic on bayes.  This will be an issue for dev or RC version.  Do we know how many students are involved in this study? (I recall that @kathy-phet was going to ask.) Has @mattpen been consulted?

**Comment by pixelzoom** [comment]
Re the QA plan:
> QA will do some testing, as will @kathy-phet, @arouinfar, and the researcher.

PhET-iO instrumentation (#85) required big changes throughout the sim. There is a very good chance that something is broken.   If that's understood by everyone, that's fine.  But I think we should all be on the same page about QA requirements.  

I'm also unclear on what "QA will do some testing" means.  I know what the process and expectations are for "Dev Test", "RC Test", and "RC-Lite Test". I do not know what "some testing" means. And it sounds like we may have more of this type of QA for more Ido studies. Can we define a name and process for this type of test, which I interpret to be less rigorous than "Dev Test"?

**Comment by pixelzoom** [comment]
3/4/21 phet-io meeting

* We will provide an RC version.
* There are a "couple of hundred" students in the study, so phet-dev.colorado.edu should be able to handle it.
* We will adopt the "RC-Research" definition.
* I will check with @KatieWoe to confirm that all test definitions are captured somewhere.

**Comment by pixelzoom** [comment]
3/11/21 phet-io meeting:

The research collaborator was provided with 1.1.0-dev.2 for review. Feedback was that it looked good. There were no change requests.

**Comment by pixelzoom** [comment]
Update: The researcher needs the link to the final version by 4/4/21.

**Comment by pixelzoom** [comment]
NOTE:  I can publish the RC version using `grunt rc`.  Work with @zepumph to create the links for QA and the researcher, so that Metacog recording will work.

**Comment by zepumph** [comment]
Note that the qa issues will likely look much like https://github.com/phetsims/QA/issues/624.

**Comment by pixelzoom** [comment]
1.1.0-rc.1 has been published and is ready for testing in https://github.com/phetsims/QA/issues/627.

**Comment by pixelzoom** [comment]
On 3/23/21, @arouinfar sent the research a link to https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet-io/, and requested feedback by Monday 3/29/21 9:00 AM MDT.

**Comment by pixelzoom** [comment]
Feedback from the research collaborator on 3/25/21:
> Hi Amy and all,
> This looks terrific - no comments from us. Thanks. 

I will proceed with the next RC (spot-check).

**Comment by pixelzoom** [comment]
Progress is blocked. I can't create the next RC due to a problem with the build server, see https://github.com/phetsims/ratio-and-proportion/issues/375#issuecomment-807400288.

**Comment by pixelzoom** [comment]
phetsims/perennial#221 is no longer blocking.

1.1.0-rc.2 was publish and is being tested in https://github.com/phetsims/QA/issues/631.

**Comment by pixelzoom** [comment]
1.1.0-rc.2 testing has been completed, see https://github.com/phetsims/QA/issues/631.  All previous issues were successfully verified. There was one new issue #113 which does not need to be addressed for this research version.

@kathy-phet @arouinfar 1.1.0-rc.2 is ready to be delivered to the research collaborator.  The link to the index wrapper is:
https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.2/phet-io

Please note in this issue when 1.1.0-rc.2 has been delivered, then close this issue.

**Comment by kathy-phet** [comment]
Thanks - will work with MK when he gets back from vacation, to make sure I send correct links for data collection and testing. On hold until March 31.

**Comment by arouinfar** [comment]
Unassigning myself since @kathy-phet will be sending the final links to the collaborator.

**Comment by zepumph** [comment]
Here are the links. Please tell our partner that each sim url is linked to a different data collection, and must be requested separately (using each sim's URL). If he would rather have a single collection to collect all data in one "pot", we can do that as well, but in my experience it can get a bit unwieldy. I also make both of these wrapper directories public, so they are ready for learner-facing testing and production.

Testing:
https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.2/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60&key_name=ido-research_2021_q2&metacog&widget_id=ido_research_molecule-polarity-test&publisher_id=0c82b6bf

Production:
https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.2/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60&key_name=ido-research_2021_q2&metacog&widget_id=ido_research_molecule-polarity&publisher_id=0c82b6bf

I also realized that in https://github.com/phetsims/special-ops/issues/189 I didn't fully document the delivery to our partner, so I did that here for both molecule polarity and build an atom.

**Comment by zepumph** [comment]
I don't want phet-io links in public issues, so I made https://github.com/phetsims/special-ops/issues/195 for the delivery, please see there. Closing.
