### ISSUE TITLE
Exclude Real Molecules screen from PhET-iO research version

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#88]
Related to #85 and #87...

@kathy-phet would like to remove the _Real Molecules_ screen from the PhET-iO version that will be provided to the research collaborator.  

I will implement this temporarily, and restore it in master after the RC branch has been created.

**Comment by pixelzoom** [comment]
_Real Molecules_ is now totally hidden in brand=phet-io.  It is unchanged in brand=phet.

**Comment by arouinfar** [comment]
Looks good in master and 1..1.0-dev.3 @pixelzoom.

**Comment by pixelzoom** [comment]
Excellent.

Leaving this assigned to me, so that I remember to revert this change after the release branch is created.

**Comment by pixelzoom** [comment]
3/4/21 design meeting:

We noticed that `moleculePolarity.global.model.surfaceColorProperty` appears in all versions, even though it's relevant only to the _Real Molecules_ screen.  We decided that was OK, and will improve the phetioDocumentation to read "color scheme for the Electrostatic Potential surface in the Real Molecules screen".

**Comment by pixelzoom** [comment]
1.1 branch was created with Real Molecules screen hidden for PhET-iO.

Real Molecules screen has been restored for PhET-iO in master.

Closing.
