### ISSUE TITLE
PhET-iO change requests (Two Molecules screen)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#89]
Related to #85... Change requests for PhET-iO instrumentation:

Uninstrument these elements:
- [x] `platesNode`
- [x] `partialCharge*Node`
- [x] `bondDipole*Node`
- [x] `molecularDipoleNode`
- [x] `arrow*Node`, the individual hint arrows
- [x] `electrostaticPotentialColorKey`
- [x] `electronDensityColorKey`

Add these query parameters:
- [x] `dipoleDirection`, values 'positiveToNegative' and 'negativeToPositive', add to [spreadsheet](https://docs.google.com/spreadsheets/d/1TddeTtD8zAayJzs02g0fL7dR1iWYczs1CMFdYd3SBNc/edit#gid=0)
- [x] `surfaceColor`, values 'RWB' and 'ROYGB', add to [spreadsheet](https://docs.google.com/spreadsheets/d/1TddeTtD8zAayJzs02g0fL7dR1iWYczs1CMFdYd3SBNc/edit#gid=0)

Studio tree structure:
- [x] Put color key elements under a common parent, `view.colorKeysNode.visibleProperty`
- [x] Fix tree structure for `electronegativityPanels`, all panels under `electronegativityPanels`
- [x] Put all "Three Atoms" listeners under `moleculeNode.dragListeners`
- [x] Put all hint arrows under `moleculeNode.hintArrowsNode`
- [x] Rename Atom.name to Atom.label, AtomNode.nameText to AtomNode.labelText
- [x] Get rid of EField class, pull `eFieldEnabledProperty` up into model.

Documentation (`phetioDocumentation`):
- [x] `angleProperty`: indicate which direction is positive
- [x] `positionProperty`: relative to the view coordinate frame, (0,0) at upper-left of layoutBounds, +x right, +y down.
- [x] `partialChargeProperty`: "qualitative scalar representation of partial charge, computed as the electronegativity difference"
- [x] `bond.dipoleProperty`: "qualitative vector representation of dipole, based on the electronegativity difference"
- [x] `molecule.dipoleProperty`: 'the molecular dipole, vector sum of the bond dipoles'
- [x] `surfaceColorProperty`: indicate that it applies to the Real Molecules screen

**Comment by pixelzoom** [comment]
I moved a couple of change requests to #91, because they are going to require significant effort. 

@arouinfar The requests in the list above are done, and ready for review in master.

**Comment by pixelzoom** [comment]
@arouinfar pointed out that I used 'RGB' instead of 'RWB' for one of the `?surfaceColor` values. Fixed in the above commit.

**Comment by arouinfar** [comment]
@pixelzoom everything is looking good in master. I'll leave this issue open and self-assigned since we still need to review the Three Molecules screen in detail.

**Comment by pixelzoom** [comment]
@arouinfar since these change requests were for the "Two Atoms" screen, I've retitle this issue to "PhET-iO change requests (Two Molecules screen)", and I'm going to close this issue.

#85 (Add basic PhET-iO instrumentation) is still open, assigned to you and @kathy-phet, and that's the appropriate place to continue your review of the "Three Atoms" screen .  If you have change requests for that screen, create another issue like this one.  Thanks!
