### ISSUE TITLE
Use a Property for Atom label

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#90]
Noticed while working on #89.

The label for Atom should be a Property, so that you can change it in one place and have it update everywhere in the view.  It is currently not a Property, can't be changed in the model, and you have to update it in multiple places in the view.

**Comment by pixelzoom** [comment]
Done in the above commit. Atom's label is now `labelProperty`.  If you change it, the labels on the atoms and in the electronegativity panels will change.  A consequence of this is that `*ElectronegativityPanel.titleText.textProperty` are now read-only.

@arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom.
