### ISSUE TITLE
Change requests for angleProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#91]
Breaking these change requests out of https://github.com/phetsims/molecule-polarity/issues/89. Investigation reveals that they are more complicated, and involve significant work. 

- [x]  Constrain these angle ranges to [-PI,PI]:
`molecule.angleProperty.rangeProperty`
`molecule.bondAngleAProperty.rangeProperty`
`molecule.bondAngleCProperty.rangeProperty`

- [x] Snap molecule`dipoleProperty` to y=0 when it's sufficiently close to zero, so that the dipole has y=0 when aligned with the e-field.

**Comment by pixelzoom** [comment]
I was thinking something like this patch in Molecule.js, but it doesn't seem quite right.

```diff
Index: js/common/model/Molecule.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Molecule.js b/js/common/model/Molecule.js
--- a/js/common/model/Molecule.js	(revision 71d5bf8bd6549bf7a33af0ba4c20fc97e9bc187d)
+++ b/js/common/model/Molecule.js	(date 1614903648961)
@@ -71,6 +71,11 @@
       this.bonds.forEach( bond => {
         sum.add( bond.dipoleProperty.get() ); // add to the same Vector2 instance
       } );
+
+      // If y is sufficiently small, snap to zero. See https://github.com/phetsims/molecule-polarity/issues/89
+      if ( Math.abs( sum.y ) < 0.00001 ) {
+        sum.y = 0;
+      }
       return sum;
     }, {
       phetioType: DerivedProperty.DerivedPropertyIO( Vector2.Vector2IO ),
```

**Comment by pixelzoom** [comment]
The molecule angle for the triatomic molecule can be a little confusing, because it's not always aligned with the molecular dipole.  So I added query parameter `showMoleculeAngle`, which adds a red arrow, with tail at the molecule position, pointing in the direction of the molecule angle.  If you need to convince yourself that `molecule.angleProperty` is correct, run with `?showMoleculeAngle`.

**Comment by arouinfar** [comment]
> Constrain these angle ranges to [-PI,PI]

The range looks good, but the polarity seems to be swapped. Normally, a positive angle is swept up from the positive x-axis (counterclockwise) while a negative angle is swept down from the x-axis (clockwise). 

The angles on the Three Atoms screen are confusing, so thanks for creating `showMoleculeAngle`.  I had to compare a few cases to figure out what's going on. It looks like `molecule.bondAngleAProperty` and `molecule.bondAngleCProperty` are always relative to `molecule.angleProperty`, so it would be helpful to state that in the documentation for both. Something like:

>angle of rotation relative to the molecule angle, in radians, with positive rotation being counterclockwise

| Scenario | Angles |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/8419308/110275012-7087db00-7f8d-11eb-92c2-e1546a77bb32.png" width=200> | `molecule.angleProperty` = 0 <br> `molecule.bondAngleAProperty` = 0.75 pi <br> `molecule.bondAngleCProperty` = 0.25 pi |
| <img src="https://user-images.githubusercontent.com/8419308/110275421-3b2fbd00-7f8e-11eb-84bb-e0b29f95364f.png" width=200> | `molecule.angleProperty` = 0.5 pi <br> `molecule.bondAngleAProperty` = 0.75 pi <br> `molecule.bondAngleCProperty` = 0.25 pi |
| <img src="https://user-images.githubusercontent.com/8419308/110276610-bc884f00-7f90-11eb-9c86-bdec452b9c85.png" width=200> | `molecule.angleProperty` = -0.5 pi <br> `molecule.bondAngleAProperty` = 0.75 pi <br> `molecule.bondAngleCProperty` = -0.5 pi |

> Snap moleculedipoleProperty to y=0 

This looks good in master. I'm no longer seeing any floating point artifacts near zero.

**Comment by pixelzoom** [comment]
> The range looks good, but the polarity seems to be swapped. Normally, a positive angle is swept up from the positive x-axis (counterclockwise) while a negative angle is swept down from the x-axis (clockwise).

All transforms in Molecule Polarity are in view coordinates, where +y is DOWN, and +angle is therefore CLOCKWISE.   I realize that this doesn't fit with math conventions, but this isn't a math sim, or something that is quantitatively exposed to the user.   And it's a well-established convention for view coordinates, a byproduct of the fact that early computers used CRT (Cathode-Ray Tube) monitors. A CRT “draws” the image with a cathode ray, scanning from the upper left corner to the lower right. To simplify/optimize the interface between the graphics-card memory and the CRT, the memory was read from the beginning and the image was drawn from the top left (cathode ray starting point, lowest memory address) to the lower right (cathode ray end point, highest memory address).  So (0,0) is at the upper left, +x is to the right, +y is down.

> It looks like `molecule.bondAngleAProperty` and `molecule.bondAngleCProperty` are always relative to `molecule.angleProperty`, so it would be helpful to state that in the documentation for both. Something like: ...

Correct, bond angles are relative to the molecule angle. I will update the phetioDocumentation as suggested.

**Comment by pixelzoom** [comment]
In Slack, @arouinfar said:
> Since it’s not a math sim, I won’t insist on swapping the polarity.

So we're going to stick with clockwise rotation.  I will put "CLOCKWISE" in caps in phetioDocumentation, since this may be unexpected. 

While changing phetioDocumentation, I noticed a few other things that could be improved. So here is a complete summary of the changes in the above commit:

* I moved "radians" out of phetioDocumentation and into the `units` option to relevant NummberProperty elements. This is the typical pattern, and I don't see a reason not to do the sane here. 

* There are a couple of problems with `bondAProperty` and `boundBProperty`.  The bonds are named `bondAB` and `bondBC`, so the naming is inconsistent. And more importantly, these Properties should be children of the bonds in the Studio tree.  So I've changed the tree structure, with `angleProperty` under each bond, and the triatomic molecule tree looks like this:

<img width="220" alt="screenshot_894" src="https://user-images.githubusercontent.com/3046552/110362667-c9438c00-7ffe-11eb-95ef-d82e81861a88.png">

* Documentation changes:

Diatomic:
`molecule.angleProperty`: rotation angle of the molecule, with positive rotation being CLOCKWISE
`molecule.bond`: the bonds that connects atoms A and B

Triatomic:
`molecule.angleProperty`: rotation angle of the molecule, with positive rotation being CLOCKWISE
`bondAB`: the bond that connects atoms A and B
`bondAB.angleProperty`: rotation angle of the bond between atoms A and B, relative to the molecule's angle and position, with positive rotation being CLOCKWISE
`bondBC`: the bond that connects atoms B and C
`bondBC.angleProperty`: rotation angle of the bond between atoms B and C, relative to the molecule's angle and position, with positive rotation being CLOCKWISE

**Comment by pixelzoom** [comment]
@arouinfar reviewed the above changes on Slack, sounds like these are all desirable changes. She'll take another pass through this.

**Comment by arouinfar** [comment]
@pixelzoom everything's looking good in master, thanks!

**Comment by pixelzoom** [comment]
Reopening. @kathy-phet reported that molecule.angleProperty is not always snapping to zero when aligned with the e-field. I observed this in master.

**Comment by pixelzoom** [comment]
Actually... I'm going to leave this closed and create a new issue.
