### ISSUE TITLE
PhET-iO change requests, continued

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-polarity#94]
For #85 and a continuation of #89.

I took another pass through the tree for both screens and found a few more things to change

- [x] `*Screen.model.molecule.atom*.electronegativityProperty` are the underlying properties for the electronegativity sliders. The slider thumb snaps to the nearest tick mark (increments of 0.2), but the value that shows up in studio occasionally reveals floating point imprecision which propagates to the properties derived from electronegativity. @pixelzoom can you round the value to the nearest 0.2? We should also remove the slider from the studio interface since it is continuous.
- [x]  `twoAtomsScreen.view.bondCharacterPanel` - uninstrument since it's just a container for a linked property which already shows up under `twoAtomsScreen.view.controlPanel.viewControls.bondCharacterCheckbox`.

Add a top-level visibleProperty to the following: 
- [x] `*Screen.view.controlPanel`
- [x] `twoAtomsScreen.view.controlPanel.viewControls` (already exists on threeAtomsScreen)

**Comment by pixelzoom** [comment]
Change requests have been completed. Back to @arouinfar for review.

**Comment by pixelzoom** [comment]
I have to say, I really dislike the electronegativity slider snapping to 0.2 while dragging.  It makes the sim feel really jerky.   Compare master to [1.1.0-dev.3](https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-dev.3/phet/molecule-polarity_en_phet.html).

**Comment by pixelzoom** [comment]
More thoughts about snapping electronegativity sliders to 0.2 while dragging...  
* Snapping to 0.2 when the slider is _released_ was added to make it easy to reproduce electronegativity settings. 
* Electronegativity range is [2,4]. Limiting to 0.2 intervals mean we have only 10 values, which seems much too coarse, and results in motion that is visibly jerky.
* Electronegativity and values derived from it are all qualitative, there ware no numeric values shown in this sim.  And values while dragging are "high frequency", which can be filtered out of the PhET-iO data stream. So other fewer message in the data stream, what are we gaining by not allowing dragging to be continous? 
* Limiting values to 0.2 does not eliminate the potential for floating point error. For example, 1.4 * 0.2 should be 0.028, but it's 0.27999999999999997 in JavaScript.
* If you still want to limit while dragging, could we snap to 0.2 on release, but snap to some smaller value while dragging?

**Comment by pixelzoom** [comment]
3/11/21 design meeting notes:

Re snapping...  I misunderstood the request.  The request is not to snap while dragging.  The problem is that the model value was not snapping to 0.2 interval on drag release.   I'll revert and investigate.

**Comment by pixelzoom** [comment]
EN slider snapping reverted to original behavior in the commit above.

**Comment by pixelzoom** [comment]
EN slider snapping is fixed in the above commit. It now snaps to 0.2 interval when the slider is release, or when you click on the track. 

@arouinfar all items in this issue are now done and ready for your review.

**Comment by arouinfar** [comment]
@pixelzoom everything looks good, closing.
