### ISSUE TITLE
Add angleABCProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#98]
3/11/21 design meeting @arouinfar @kathy-phet @pixelzoom 

Add `threeAtoms.model.molecule.angleABCProperty` with range [-PI,PI].  Positive angle clockwise, as in other places.  This is a PhET-iO only Property, added only for the data stream.

**Comment by pixelzoom** [comment]
This is done, `see moleculePolarity.threeAtomsScreen.model.molecule.boundAngleABCProperty`.  

Range is [-PI, PI).

To wrap your head around the sign of the angle, think of drawing an arc from atom A to atom C.  In keeping with the "positive rotation CLOCKWISE" convention for the coordinate frame...

An orientation like this will have a positive value:

![screenshot_200](https://user-images.githubusercontent.com/3046552/110868704-4af91b00-8286-11eb-8f94-d0a9d8399d50.png)

An orientation like this will have a negative value:

![screenshot_201](https://user-images.githubusercontent.com/3046552/110868828-8562b800-8286-11eb-91cf-a81306ba190b.png)

@arouinfar @kathy-phet please review.

**Comment by arouinfar** [comment]
@pixelzoom looks like there's a typo in the phetioID, it's currently `boundAngleABCProperty` instead of `bondAngleABCProperty`. Otherwise, this looks good in master, and I think the sign convention is clear and matches what @kathy-phet suggested in design meeting.

**Comment by pixelzoom** [comment]
Thanks @arouinfar, good catch on the typo.  Fixed in the above commit, Studio screenshot below. Closing.

![screenshot_209](https://user-images.githubusercontent.com/3046552/111542195-06162e00-8737-11eb-907a-4af8fd6713f0.png)
