### ISSUE TITLE
Describe view coordinate frame in relevant phetioDocumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#99]
3/11/21 design meeting @arouinfar @kathy-phet @pixelzoom 

We discussed adding a model-view transform that flips the y-axis, and then specifying the model in the typical "+y up, +angle counterclockwise" convention.   But since this sim has no model-view transform, that would be a major change, possibly destabilizing. So...

Add “+x right, +y DOWN” to `phetioDocumentation` for all relevant Vector2 and scalar Properties.

**Comment by pixelzoom** [comment]
Done in the above commit.  Here are the changes:

`atom*.positionProperty`:
'The position of this atom. (0,0) is at the upper-LEFT, +x is to the right, and +y is DOWN.'

`molecule dipoleProperty`:
'The molecular dipole, vector sum of the bond dipoles. +x is to the right, +y is DOWN, and positive rotation is CLOCKWISE.'

`bond*.dipoleProperty`:
'Qualitative vector representation of the dipole, based on the electronegativity difference between the atoms. +x is to the right, +y is DOWN, and positive rotation is CLOCKWISE.'

@arouinfar or @kathy-phet please review in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Looks good in master.
